### ISSUE TITLE
Always provide pootle-terminology as an upload target for admins

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#1752]
*Version: 2.1.x*

When a user wants to upload a terminology file into a project where there isn't one yet, they have to use the correct name. However, if we can list pootle-terminology.ext in the list of target file names, we can make it easier to use any file they have as the terminology file.

**Comment by dwaynebailey** [comment]
Since we've dropped the idea of generating a ``pootle-terminology.po``, although we still use them.  But we also do upload and download differently and do allow term file to be uploaded and downloaded.  I'm going to close this and we can address any terminology concerns in the current implementation instead.
