### ISSUE TITLE
Reject or accept a suggestion with more options (e.g. comment)

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2596]
Currently we can easily reject or accept a suggestion and the unit moves on.

We need to refine this behaviour so that there are more possibilities of what you can do:
## Actions:
- Reject All - reject all this users suggestions.  With the option of blocking
- Reject with comment - we don't allow someone to comment on why they rejected.  To create community we should give feedback
- Accept with comment - sometimes its nice to be appreciated when you contribute
- Accept and edit - we currently move on to the next unit, but maybe you want to actually use the suggestion but make some simple changes.  The idea being that this would then still credit the suggestor.
- Accept One and Reject Others - a single action should allow you to accept a single unit with a comment and reject all others. This saves you time when when there are e.g. 3 suggestions and you keep having to come back to the unit to cleanup.

**Comment by Jobava** [comment]
I am adding these from the duplicate feature request I made earlier:

1. Notify the contributor that their suggestions were rejected or accepted (perhaps daily, weekly, selectable from the user's settings).

2. Give contributors a unified view of their contributions and why they were rejected, if there is a reason attached.

3. Create a list of "canned motives" for reviewers to use, locale-specific, admin-modifiable, which reviewers could select from a dropdown or some other UI metaphor to speed up review and encourage feedback. Example: misspelled, false friends, terminology violation, wrong style, spam/unhelpful etc.

Numbers 1 and 2 could be incorporated into some sort of "user's dashboard" or similar metaphors.

**Comment by iafan** [comment]
I'd recommend to decouple the "comment on an action" task with the task of approving/rejecting the suggestion (this will make the UI more simple). If I want to comment on e.g. suggestion, I should be able to do so without having to approve or reject it using some special mode. I may also want to reject a suggestion and, on a second thought, add some extra comment.

If we implement a consistent user feedback functionality (see https://github.com/translate/pootle/issues/4631) this will naturally address "Reject with comment", "Accept with comment" and "comment without accepting or rejecting" use cases, and can be done pretty easily if implemented via email (not via some sort of in-Pootle private messaging).

**Comment by dwaynebailey** [comment]
@iafan re decoupling.  I think it does lead to a simpler UI, whatever we created was too complicated.  

But I have some reservations as a long term approach and wanted to raise some issues that are of concern to u:

1. Using email we're opening an avenue which is open to abuse (coupled with a notification system, this would be eliminated i.e. no direct emailing)
2. We're relying on a form that is way too generic when we actually just want feedback and not to overwhelm the reviewer with too many options such that they give no feedback.
3. The reviewer gets taken out of the editor if they're giving feedback which breaks the rhythm and will I fear lead to less feedback in the long term.
4. Ideally we'd want reviewers to almost always give feedback, even if it's just a thanks.  With this model reviewers have to intentionally give feedback.  I don't know how to get around this as all our thoughts on UI made it cumbersome if we forced feedback.
5. Its not discoverable, you need to know that clicking on the Avatar would allow you to communicate. (A extra feedback button on the suggestion could address this)

**Comment by iafan** [comment]
Obviously, if you are up to implementing in-Pootle private messaging, this will eliminate many of your concerns (1, 6, 7 on your list). But that's a pretty large project, so I thought it makes sense to use the existing solution that we already have (to allow people to communicate at all) before going with the embedded messaging.

Since we use a lightbox dialog (overlay) for generic messages, I think it doesn't really break the rhythm: our translators use such messaging a lot to report problems with strings, and use this very often, and we've always got only positive feedback on this. So my assumption, backed with the extensive usage, is that such flow actually works pretty good and doesn't distract translators from the main translation tasks. Of course, it doesn't mean that it is better than any specific feedback UI that would address (2) and (4). But I think it should be there nonetheless (at least for generic discussions) even if we decide to implement some specific feedback UI.

Re (5) I already suggested in #4631 that we might want to use hover instead of a click for better discoverability. If this is not enough, then yes, we will need to have something more explicit.

**Comment by ta2-1** [comment]
@iafan I don't see any reason why we can't show any other feedback form instead of contact form if we decide to use a lightbox dialog. And the simplest solution which we always think about but don't like is to add more circle buttons (`accept with comment`, `reject with comment`, `accept`, `reject`). Can these buttons be shown (expanded) by user action probably?

**Comment by iafan** [comment]
> I don't see any reason why we can't show any other feedback form instead of contact form if we decide to use a lightbox dialog.

Yes, we can do that as well. I'd suggest we do both:
1. generic feedback form if one wants to write something arbitrary to the user
2. suggestion-specific UI to provide feedback (which should probably not use the lightbox dialog at all).

Before just adding more action buttons (which is definitely not the best UI choice as I currently see it) let's think what kind of feedback you would like to provide in the first place. For example, see what MateCat is doing to provide per-unit feedback (which somewhat correlates to what @Jobava suggested):

![screenclip](https://cloud.githubusercontent.com/assets/1728158/14361081/1dd335ec-fcae-11e5-95d8-cc3e579e5621.png)

We could implement some similar in-context feedback form when going through suggestions. But since this is a more involving task, I'd recommend implementing the generic feedback form as a first step, then tackle the second phase.

**Comment by ta2-1** [comment]
In #4659 we allowed yo leave comments on accepting/rejecting. But this issue is wider. So I'm adding this mockup from @iafan here which can be used to address this issue for 100%.
![image](https://cloud.githubusercontent.com/assets/682845/17552130/a4d97244-5f06-11e6-9a22-8a29872a600e.png)

**Comment by unho** [comment]
Note that feedback needs to be properly notified as well: #5041.

**Comment by ta2-1** [comment]
We already can "Reject with comment", "Accept with comment", "Accept and edit".
There is suggestions admin ui for bulk operations over suggestions.
Notification system is a separate task.
