### ISSUE TITLE
Plural field goes missing when uploading file

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#3050]
*Version: 2.5.0*

*Originally posted by Henrik:*

*Created [attachment 940](http://bugs.locamotion.org/attachment.cgi?id=940)*

Empty .ts file

Problem seem with Qt ts files. I could not reproduce with .po files

Howto reproduce:
1) untranslated .ts file with plural field
2) translate .ts file offline and upload to project. Merge with current file

Expected outcome:
Both translated fields are visible from pootle

Actual:
Only one translation field is visible. However translation is not lost. Update against templates will return the field and translations are still present.

Attaching two simple .ts files to help with reproducing the bug

**Comment by phlax** [comment]
This is a very old bug, so rather than test it on 2.5 I decided to find out if it was still relevant.

Attempting to upload a .ts file gets the error:

"'tsfile' object has no attribute 'parseheader'"

Looking through the code it seems that its no longer possible to upload any filetype other than .po, as only po files have the parseheader method.

As this needs to be fixed first, I have raised a ticket for this problem here #3966

**Comment by ta2-1** [comment]
To test this on current master I had to import .ts file manually via `./manage.py shell` similar like it's done in test from this commit https://github.com/translate/pootle/commit/f93a5805e65386c3ed264c9df70fe21984fb852e. 
Now I reckon that unit with plurals imported from .ts file is rendered correctly and all plural fields are visible and close the issue.
