### ISSUE TITLE
Add option to automatically reject translations that don't pass quality checks

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#3114]
*Originally posted by Robin Veeck:*

I'm interested in adding the option to refuse to submit translations that don't pass the quality check suite. Right now, our translators often don't notice the warnings generated by check failures. Some check failures (such as changed variable names) can break our build or fail silently on the site. The translation is tagged for review, but since Pootle automatically opens up the next translation after submission our translators often don't see the warnings. 

We'd like translators to see an error message when their translation doesn't pass the pofilter checks, and be unable to submit until they have fixed the problem.

**Comment by jleclanche** [comment]
@julen I'm closing this since we do this in core (please reopen if I'm wrong)

**Comment by iafan** [comment]
For the record, we don't reject submissions (because we don't want people to lose their translations just because of some typo), but if a new check is triggered on submission, we highlight the unit row with red, and don't advance the user to the next unit, thus asking them to deal with the problem first. Please note that some checks may have false positives, and such issues shouldn't prevent users from submitting translations as well.

**Comment by jleclanche** [comment]
That seems like the right way to do it anyway.
