### ISSUE TITLE
Creating a new language should calculate stats

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3235]
When creating a fresh language we are not currently calculating statistics for it. Needs to be fixed for 2.6.

**Comment by unho** [comment]
@julen Is this an issue on the new master?

**Comment by unho** [comment]
@julen Is this an issue on the new master?

**Comment by phlax** [comment]
i believe this may have already been fixed in #4218

**Comment by unho** [comment]
This is a good candidate to add a test for it.

**Comment by phlax** [comment]
ref #4231

**Comment by ta2-1** [comment]
This is not an issue after we've forbidden to add new languages for projects without templates in 
3f15745577e42dd538c2f1662e9fddbb092302f8.
If we add new language for a project with templates, stats will be filled properly (fixed in 82295d6).
We can close this issue, but tests are very needed here.
