### ISSUE TITLE
Capability for versions in projects

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#337]
_Version: 0.6.3_

_Originally posted by Oscar Manuel Gómez Senovilla:_

This is a RFE. I think that products (projects) should have a way to create
versions inside themselves, before passing to the language. So, I think instead
of the current structure po/$project/$language, it should be something like
po/$project/$version/$language.

There are strong reasons for this. Take that, for instance, you have to choose
among one of the existing in
ftp://ftp.linux.cz/pub/localization/OpenOffice.org/devel/POT/2.0.1/, and it's no
good to create different projects and not to take profit of previous work.

A related issue (not sure if it's for another bug, or not a bug at all) is to
import a translation of a previous version of the same language.

**Comment by linuxjackto1** [comment]
thanks www.movied.org

**Comment by pascalrobert** [comment]
As asked in the Gitter group, I'm adding my comment:

One of our teams is using Git-flow, so they have translations in multiple branches (mostly two branches). Currently, we have one project per branch in Pootle, which is not optimal since our translators need to check both projects. Any suggestions on how we can have one project in Pootle with .po/.pot files coming from multiple branches? Something similar to posummit (http://pology.nedohodnik.net/doc/user/en_US/ch-summit.html) would be great.

**Comment by phlax** [comment]
hi @pascalrobert looks like a good feature. We are currently beta-testing pootle_fs which brings back vcs functionality. I will take a better look at your suggestion as we continue to work on it.

**Comment by comradekingu** [comment]
It is now possible to upload an old branch onto a new one, instead of adding complexity, the proposed solution is #6854
