### ISSUE TITLE
RQ stats getting stuck in a count loop

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3409]
While demoing the [staging server](https://core-translate.stage.evernote.com/fr/android_evernote/) I made a translation change and this then showed up the "Some data on this page is currently being calculated, and the page will be refreshed automatically in 12 seconds. Refresh now" on the overview page.

The stats remain stuck in a refresh stats state and seem not to ever complete their update.

**Comment by dwaynebailey** [comment]
I'm closing this as so much has changed in RQ and unless I can replicate its hard to define

**Comment by imankulov** [comment]
Just a note for the record. I hit the same issue at least twice during the installation process (I installed and re-installed Pootle many times). Probably it happened because I tried to update data in some projects in parallel, or cancelled my import with Ctrl+C mid-way, I'm not sure.

I investigated a bit, and found out that data look consistent (except for that annoying issue), and I had no pending or failed job in the queue, so I just decided to reset that dirty flag. My recipe in case anyone stumbles upon the same.

```
$ pootle shell
>>> from django_rq.queues import get_connection
>>> POOTLE_DIRTY_TREEITEMS = 'pootle:dirty:treeitems'
>>> c = get_connection()
>>> keys = c.zrangebyscore(POOTLE_DIRTY_TREEITEMS, 1, 1000000)
>>> updates = {k: 0.0 for k in keys}
>>> c.zadd(POOTLE_DIRTY_TREEITEMS, **updates)
```

**Comment by julen** [comment]
Thanks for sharing @imankulov. You might at the same time want to keep an eye on #4219.

**Comment by imankulov** [comment]
@julen thanks for the hint! Subscribed for both #4216 and #4219 :)

**Comment by olaputin** [comment]
@imankulov Thanks for your solution.
