### ISSUE TITLE
Completely get rid of profile references

### ISSUE THREAD

**Issue by unho** [translate/pootle#3459]
Like `request.profile`.

**Comment by jleclanche** [comment]
cc @julen 
This is something I addressed over several commits in master, including:

d355b9a76a8fece705ab4cce31e892fdec851520
967925231e24d837590cc08051207b61c351feef
a4a0ee6688c84ca57c501ec7b751a9e24e0a8096
29aca838fe8276fcefa020d63b13c613ba7ab162
a433c7f4e1ef82a347c97a1ee74742e1b29317cb
eca2333d07da5a7168b98153c7499a7944137f1d
18cf1f826d4e90e0928e9d4e00eff75e9e901619

Are you ok with this approach?

**Comment by julen** [comment]
Being from an era where `PootleProfile` existed, I don't see *much* relevance in those commits. Most of the references were already changed when migrating away from `PootleProfile`.  #3455 is relevant here.

Another thing to note is that blindly renaming `request.profile` → `request.user` doesn't work, because when anonymous users are involved the *nobody* user has to be retrieved (Django otherwise returns its own `AnonymousUser`).

**Comment by jleclanche** [comment]
Noted. Will see what can safely be moved and write down the rest.

**Comment by julen** [comment]
My initial idea for this was overriding `request.user` in a middleware, doing `request.user = User.get(request.user)` — the class method takes care of returning the *real* user. From that point onwards it'd be safe to use `request.user` everywhere, plus there's no need to handle this special-casing in views.

I didn't have time to address (and test) this because there were other priorities at the time, so I'm not sure if this has other unwanted consequences or conflicts with other middlewares in the pipe. Also note that `request.user` is a proxy (`SimpleLazyObject`) to the actual objects.

**Comment by unho** [comment]
I fail to see the relevance of https://github.com/translate/pootle/issues/3455 here, but I agree with the rest.

**Comment by julen** [comment]
The title says *Completely get rid of profile references* and #3455 is just another (type of) reference to *profile*.
