### ISSUE TITLE
Get rid of docs on 2.6.0

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3494]
We should document that 2.6 is an interim release and that means removing all public docs from stable/2.6.0

**Comment by dwaynebailey** [comment]
@jleclanche please add comments when you close.

**Comment by dwaynebailey** [comment]
Doesn't make sense. 2.6.0 is an interim release and it doesn't make sense to cleanup docs that we won't even publish.

**Comment by unho** [comment]
@dwaynebailey I think this is might be worth opening. Upgrade instructions for 2.6 differ from any other version since they are focused on providing the upgrade for 2.7 and later. See http://docs.translatehouse.org/projects/pootle/en/stable-2.6.0/server/upgrading.html

Of course one might say that those can be merged into 2.7 upgrade instructions, but then those will be quite extensive and will drag the specifics for 2.6 upgrade release after release. A compromise solution might be to don't publish 2.6 docs, and move 2.6 upgrade to 2.7 (and later) docs, but keeping it as a separate page.

**Comment by jleclanche** [comment]
2.6 should probably redirect to 2.7.

**Comment by unho** [comment]
Not necessary if it is just disabled on ReadTheDocs.
