### ISSUE TITLE
Differentiate between disabled and hidden projects

### ISSUE THREAD

**Issue by julen** [translate/pootle#3530]
Projects have the `disabled` field (40da23079 & a6b5dd9d), but it has resulted to be confusing — since it has effects on the UI, lots of times it's unclear the purpose of setting that bit on. In other words, it's difficult to know if a project is only *hidden* from the UI, or actually *disabled* from any sort of processing.

By adding a new `hidden` field for projects and translation projects, it'd be easy to distinguish between both scenarios, and the code would result to be much more explicit.

This can be summarized as:
- *enabled* and *visible*: standard situation, accessible for whoever has access rights to it
- *enabled* and *hidden*: stats still kept, admins can access and browse it, other users get 404 and cannot see them in listings
- *disabled*: no stats calculated, used for gone projects and archival purposes, implies being hidden for everyone when browsing (even admins), resulting in 404. It's only listed in the admin UI.

**Comment by iafan** [comment]
As per our today's talk, I think we'd better keep this as is: disabled project should simply mean that it should be hidden from anybody expect admins, but otherwise it should be a regular project, with stats being kept, displayed and updated.

The idea behind having a disabled project was to hide the project from translation for anybody (especially at project creation time); do the maintenance, setup permissions, update stats, then be able to open it with the flip of the switch, without messing with permissions and permission overrides. Or keep it disabled forever for archived projects (but for admins still to be able to peek into its details/history).

Regarding terminology, I don't like the term _hidden_ (or _visible_), because projects can also be hidden due to permission restrictions.

So the project is _hidden_ because either user has no permissions, or because it was explicitly _disabled_ by admins. "_disabled_" is a project property, and "_hidden_" is an end result.

**Comment by ta2-1** [comment]
> but for admins still to be able to peek into its details/history

@iafan what does "history" means? Timeline?
It seems we got exactly what you asked.
Can you look at my [comment](https://github.com/translate/pootle/pull/4008#issuecomment-134645914)?

**Comment by iafan** [comment]
history = how the project looked like before it was disabled. Tree structure, stats, stores, units, their translations and their timeline.

**Comment by ta2-1** [comment]
Then admins will be able to translate units in disabled projects. Is it ok?

**Comment by iafan** [comment]
I think that is ok. "Disabled" == "globally hidden for anybody expect admins, but otherwise functional."

**Comment by julen** [comment]
Closing per the decision already made.
