### ISSUE TITLE
Language code ca@valencia not being parsed

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3549]
If you use the language code ``ca@valencia`` then Pootle is not picking up the project.  It doesn't process it in update_stores or in refresh_stats.  This language is present Pootle's default Terminology project.

I'm not sure if this is caused by some parsing of language names and the presence of @ in the name.

**Comment by dwaynebailey** [comment]
@iafan julen mentioned that you might be the right person to bounce this off, have you seen similar issues?

**Comment by julen** [comment]
Having a quick look, you mention you're using the default Terminology project, and as I see there's no `ca@valencia` directory there.

If you read the [docs for `update_stores`](http://docs.translatehouse.org/projects/pootle/en/latest/server/commands.html#update-stores), TPs that don't exist on-disk anymore will be disabled. So this is expected behavior and has nothing to do with the locale code being used (FWIW we made no modifications to the regexps there).
