### ISSUE TITLE
Simplify and cleanup license header

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3609]
The license headers are noisy and I'd like to make them use and throw away.  Credits for work already exist in ``git log``.

This work would include:

* Creating a standard header (needs unification of current GPL versioning)
* Updating and validate header dates
* Creating some sort of AUTHORS which can spell out licensing history and ownership
* #2654 move to GPL3 (possibly)

**Comment by jleclanche** [comment]
Does GPL *require* us to have a license header at the top of every file? As a programmer, there is nothing I hate more than boilerplate that takes space and needs to *regularly be updated* instead of the tools we already have: that is, a LICENSE/AUTHORS file and a git log.

It's so incredibly stupid every file that contains a single import line needs to have 50 lines of boilerplate.

**Comment by jleclanche** [comment]
It seems very hard to find answers on the net as to why such an incredibly stupid system is in place. I did find a few SO topics though.

FWIU, the license header needs to be there because in case the file is separated from the rest of the project. So, again from what I understand, we can go for something like the following:

```py
# This file is a part of Pootle <http://pootle.translatehouse.org/>. It is
# distributed under the GPL2 license. Please see the LICENSE file for a copy of
# the license and the AUTHORS file for copyright and authorship information.
```
