### ISSUE TITLE
Chinese interface language of pootle cannot display completely[2.5.1.1]

### ISSUE THREAD

**Issue by shouhuanxiaoji** [translate/pootle#3624]
![qq 20150306132040](https://cloud.githubusercontent.com/assets/4121607/6520608/0001b66c-c404-11e4-95cb-3a159862ee89.png)
![qq 20150306132122](https://cloud.githubusercontent.com/assets/4121607/6520609/00f09e12-c404-11e4-814a-cf1891c0cc74.png)
Hello, all my friends.I have built a pootle on my vps.But after building ok, I found that the interface of pootle is part of english and part of Chinese——it means that some Chinese words can not display completely(like images above).
I can conform it can display chinese interface and the 'password' has display '密码'.
I want to know why and how to solve this question.
Thanks!

**Comment by dwaynebailey** [comment]
hi @shouhuanxiaoji this is potentially because of two issues:

1. Try this first, the files are not compiled.  Try ./setup.py build_mo --all
2. The translations for both zh_TW and zh_CN are not 100% complete - in this case you'd need to complete the translations in ``pootle/locale/zh_TW/*.po`` and do step 1.

**Comment by shouhuanxiaoji** [comment]
After I done what you said.The interface has also the same problem.
should I copy the .mo files to some directories?

**Comment by shouhuanxiaoji** [comment]
sorry,I have solved this question.After I reboot the uwsgi service.The interface has display Chinese.
