### ISSUE TITLE
Source directory layout reorganization

### ISSUE THREAD

**Issue by julen** [translate/pootle#3656]
In terms of Django-specific code, Pootle's directory layout is a mix of years of work with no established pattern and legacy code. There's a **common will to reorganize** that.
## Current situation

Taking a general overview, the situation can be summarized as follows:
- Almost every model/view lives in a separate app: `pootle_language`, `pootle_project`, `pootle_translationproject`, etc.
- Some models/views live in a general `pootle_app` app: `Directory`, `Permission`.

Historically, the `pootle_*` apps were aimed to be reusable, but continuous development has shown it to be a dead end: in most of the cases the models from these apps have constant inter-dependencies, and are tightly coupled one with each other (`Store` → `Submission`, `TranslationProject` → `Directory`, `Store` → `User` etc.). Having them spread across applications has no mutual benefit.

There are legitimate cases for having models in separate apps: apps that are focused in a single specific task and are decoupled from Pootle's core functionalities. In other words, Pootle can run without these apps just fine because they provide **extra functionality** on top of the base set by the core.
## Goals

Reorganization should strive for:
1. **Removing excessive split** in applications by gathering core Pootle components in a single location: these are tightly coupled.
2. Keeping applications that provide **extra functionality explicitly separate**.
3. **Restructuring** project's layout to better reflect the previous changes and the nature of its components.
#### Should be gathered as part of core
- `pootle_app` is something similar to a Pootle core app. Actually models and views from here were taken out piece by piece (5b2541638f) in order to make them _"reusable apps"_.
- `pootle_language` has the `Language` model, and some language-related views, but not necessarily language-specific (overview, editor, export view, permissions).
- `pootle_project` has the `Project` model, and some project-related views, but not necessarily project-specific (overview, editor, export view, permissions).
- `pootle_translationproject` has the `TranslationProject` model, and some translation project-related views, but not necessarily translation project-specific (overview, editor, export view, permissions).
- `pootle_statistics` includes the `Submission` and the `ScoreLog` models that track the events and score changes for `Unit` models.
- `accounts` includes the `User` model.
- `pootle_profile` contains views that deal with the `User` model: user's public profile, user's settings, and XHR API to deal with it. This used to be home for the now gone `PootleProfile` model.
- `pootle_store`: has the `Unit`, `Store`, `Suggestion` and `QualityCheck` models. This is Pootle's real data store. It also includes views for the internal XHR API that is consumed by the overview pages and the translation editor.
- `pootle_misc` is a collection of utilities and helpers that can be used by any component.
  - These should live within `pootle.core`, `pootle.core.utils` or similar.
  - `templatetags` should be moved to `pootle.templatetags` or `pootle.core.templatetags`.
#### Uncertain
- `pootle_terminology` contains views that handle the terminology feature for translation projects. It also contains some logic belonging to models, but since there's no `Terminology` model, it misuses the `Unit` model for that. The whole app is a terrible hack and its purpose should be rethought altogether.
### Extra functionality apps are separate

These apps can be kept as they are, even though **they might need some extra work** to have them completely decoupled from the Pootle core. At the same time, Pootle's core should provide extra mechanisms to make the integration of components like these easier.
- `contact`
- `import_export`
- `reports` (rename away from `evernote_reports`)
- `staticpages`
#### What lives where

Taking all the previous points into account, first of all we need to determine where do core and extras live.
##### Where does core live?
- **Project-level**: Pootle's project-level directory can be be considered as the core (NB: this is the reason why the custom `User` model was put in `pootle.models`, anticipating [plans to greatly refactor the backend models](https://docs.google.com/a/evernote.com/document/d/13BOHsdiM6KDc07YWK_ehTDOHjDnpIvtGay4IPdgxM_I/edit) in 2014).
  This makes it very simple to refer to core models and other components both from internal and external code. There's also no need to include anything special to make imports work.

``` python
from pootle.models import TranslationProject, Unit
```

as opposed to the current form (note that _apps_ needs to be explicitly put into Python's search path):

``` python
from pootle_store.models import Unit
from pootle_translationproject.models import TranslationProject
```
- **Project submodule**: a separate `core` submodule can serve as the home for core components. This is slightly more verbose than the previous option but also explicit.

``` python
from pootle.core.models import TranslationProject, Unit
```

Note that there already exists a `pootle.core` module which contains code and utilities which are shared across all of the existing apps. If going this route, the location of some of these modules _might_ need to be reconsidered.
##### Where do extras live?
- Separate repository  
  Every extra non-core component could live in a separate repository therefore reassuring the independence with the core. [django-cms does this](https://github.com/divio/) for example.
- Within the repository  
  This is another way of saying the extra components are _officially supported_. Regarding the actual location within the repository, there are different options:
  - `apps` subdir  
    This is the current _"approach"_. Every single Django app lives under this subdirectory.  
    _(Historical note: this was split into `local_apps` and `external_apps`, but then when pip and requirements files emerged the external apps were made dependencies and everything converged into `apps`, as the distinction of local vs external made no difference)_
  - `plugins` subdir  
    This would be an option that stresses that extras provide something more than a mere Django app, because in the end Pootle core wants to offer ways to better extend and integrate with it: plugging URLs without messing up with core `urls.py`, hooking points in code, and so on.  
    _(Note: `plugins` is a proposed example, but any other name (besides app) that expresses the different nature of these components can be used.)_
#### Proposed layouts
1. Core at project-level, extras in `plugins` dir
   
   ```
   ├── __init__.py
   ├── apps.py
   ├── core
   ├── dbs
   ├── forms
   ├── i18n
   ├── locale
   ├── log
   ├── management
   │   └── commands
   ├── managers
   ├── middleware
   ├── migrations
   ├── models
   ├── plugins
   ├── po
   ├── runner.py
   ├── settings
   ├── settings.py
   ├── static
   ├── templates
   ├── templatetags
   └── views
       ├── admin
       ├── api
       ├── editor.py
       ├── export_view.py
       ├── index.py
       ├── overview.py
       ├── terminology.py
       └── urls.py
   ```
   
   Expanded one level deeper:
   
   ```
   ├── __init__.py
   ├── apps.py
   ├── core
   │   ├── __init__.py
   │   ├── cache.py
   │   ├── checks.py
   │   ├── context_processors.py
   │   ├── decorators.py
   │   ├── exceptions.py
   │   ├── helpers.py
   │   ├── initdb.py
   │   ├── log.py
   │   ├── markup
   │   ├── mixins
   │   ├── runner.py
   │   ├── stats.py
   │   ├── storage.py
   │   ├── tmserver.py
   │   ├── url_helpers.py
   │   ├── utils
   │   └── views.py
   ├── dbs
   ├── forms
   │   ├── captcha.py
   │   ├── fields.py
   │   ├── language.py
   │   ├── project.py
   │   ├── search.py
   │   ├── unit.py
   │   └── user.py
   ├── i18n
   ├── locale
   ├── log
   ├── management
   │   ├── __init__.py
   │   └── commands
   ├── managers
   │   ├── __init__.py
   │   └── user.py
   ├── middleware
   │   ├── __init__.py
   │   ├── baseurl.py
   │   ├── cache.py
   │   ├── captcha.py
   │   ├── errorpages.py
   │   └── setlocale.py
   ├── migrations
   │   ├── 0001_initial.py
   │   ├── 0002_migration.py
   │   ├── 0003_migration.py
   │   └── __init__.py
   ├── models
   │   ├── __init__.py
   │   ├── directory.py
   │   ├── language.py
   │   ├── permissions.py
   │   ├── project.py
   │   ├── quality_check.py
   │   ├── revision.py
   │   ├── scorelog.py
   │   ├── store.py
   │   ├── submission.py
   │   ├── suggestion.py
   │   ├── translation_project.py
   │   ├── unit.py
   │   ├── user.py
   │   └── virtualfolder.py
   ├── plugins
   │   ├── __init__.py
   │   ├── contact
   │   ├── import_export
   │   ├── reports
   │   └── staticpages
   ├── po
   │   ├── terminology
   │   └── tutorial
   ├── settings
   ├── settings.py
   ├── static
   │   ├── css
   │   ├── favicon.ico
   │   ├── images
   │   └── js
   ├── templates
   │   ├── about.html
   │   ├── admin
   │   ├── browser
   │   ├── core
   │   ├── editor
   │   ├── errors
   │   ├── languages
   │   ├── layout.html
   │   ├── projects
   │   ├── translation_projects
   │   ├── user
   │   └── welcome.html
   ├── templatetags
   │   ├── __init__.py
   │   ├── baseurl.py
   │   ├── cleanhtml.py
   │   ├── common.py
   │   ├── locale.py
   │   ├── render_pager.py
   │   ├── search.py
   │   ├── unit.py
   │   └── user.py
   └── views
       ├── __init__.py
       ├── admin
       │   ├── __init__.py
       │   ├── dashboard.py
       │   ├── languages.py
       │   ├── permissions.py
       │   ├── projects.py
       │   └── users.py
       ├── api
       │   ├── languages.py
       │   ├── projects.py
       │   ├── stats.py
       │   ├── store.py
       │   ├── suggestion.py
       │   ├── units.py
       │   └── user.py
       ├── editor.py
       ├── export_view.py
       ├── index.py
       ├── overview.py
       ├── terminology.py
       └── urls.py
   ```
2. Core at project submodule, extras in `plugins` dir.
   
   2.1 only model-relateds in `core`:  
   
   ```
   ├── __init__.py
   ├── apps.py
   ├── core
   │   ├── models
   │   ├── managers
   │   └── migrations
   ├── dbs
   ├── forms
   ├── i18n
   ├── locale
   ├── log
   ├── management
   │   └── commands
   ├── middleware
   ├── plugins
   ├── po
   ├── settings
   ├── settings.py
   ├── static
   ├── templates
   ├── templatetags
   └── views
       ├── admin
       ├── api
       └── urls.py
   ```
   
   Expands to:
   
   ```
   .
   ├── __init__.py
   ├── apps.py
   ├── core
   │   ├── __init__.py
   │   ├── cache.py
   │   ├── checks.py
   │   ├── context_processors.py
   │   ├── decorators.py
   │   ├── exceptions.py
   │   ├── helpers.py
   │   ├── initdb.py
   │   ├── log.py
   │   ├── management
   │   │   ├── __init__.py
   │   │   └── commands
   │   ├── managers
   │   │   ├── __init__.py
   │   │   └── user.py
   │   ├── markup
   │   │   ├── __init__.py
   │   │   ├── fields.py
   │   │   ├── filters.py
   │   │   └── widgets.py
   │   ├── migrations
   │   │   ├── 0001_initial.py
   │   │   ├── 0002_migration.py
   │   │   ├── 0003_migration.py
   │   │   └── __init__.py
   │   ├── mixins
   │   │   ├── __init__.py
   │   │   ├── dirtyfields.py
   │   │   └── treeitem.py
   │   ├── models
   │   │   ├── __init__.py
   │   │   ├── directory.py
   │   │   ├── language.py
   │   │   ├── permissions.py
   │   │   ├── project.py
   │   │   ├── quality_check.py
   │   │   ├── revision.py
   │   │   ├── scorelog.py
   │   │   ├── store.py
   │   │   ├── submission.py
   │   │   ├── suggestion.py
   │   │   ├── translation_project.py
   │   │   ├── unit.py
   │   │   ├── user.py
   │   │   └── virtualfolder.py
   │   ├── runner.py
   │   ├── stats.py
   │   ├── storage.py
   │   ├── tmserver.py
   │   ├── url_helpers.py
   │   ├── utils
   │   │   ├── __init__.py
   │   │   ├── dateparse.py
   │   │   ├── templates.py
   │   │   ├── timezone.py
   │   │   └── wordcount.py
   │   └── views.py
   ├── dbs
   ├── forms
   │   ├── captcha.py
   │   ├── fields.py
   │   ├── language.py
   │   ├── project.py
   │   ├── search.py
   │   ├── unit.py
   │   └── user.py
   ├── i18n
   ├── locale
   ├── log
   ├── middleware
   │   ├── __init__.py
   │   ├── baseurl.py
   │   ├── cache.py
   │   ├── captcha.py
   │   ├── errorpages.py
   │   └── setlocale.py
   ├── plugins
   │   ├── __init__.py
   │   ├── contact
   │   ├── import_export
   │   ├── reports
   │   └── staticpages
   ├── po
   │   ├── terminology
   │   └── tutorial
   ├── settings
   ├── settings.py
   ├── static
   │   ├── css
   │   ├── favicon.ico
   │   ├── images
   │   └── js
   ├── templates
   │   ├── about.html
   │   ├── admin
   │   ├── browser
   │   ├── core
   │   ├── editor
   │   ├── errors
   │   ├── languages
   │   ├── layout.html
   │   ├── projects
   │   ├── translation_projects
   │   ├── user
   │   └── welcome.html
   ├── templatetags
   │   ├── __init__.py
   │   ├── baseurl.py
   │   ├── cleanhtml.py
   │   ├── common.py
   │   ├── locale.py
   │   ├── render_pager.py
   │   ├── search.py
   │   ├── unit.py
   │   └── user.py
   └── views
       ├── __init__.py
       ├── admin
       │   ├── __init__.py
       │   ├── dashboard.py
       │   ├── languages.py
       │   ├── permissions.py
       │   ├── projects.py
       │   └── users.py
       ├── api
       │   ├── __init__.py
       │   ├── languages.py
       │   ├── projects.py
       │   ├── stats.py
       │   ├── store.py
       │   ├── suggestion.py
       │   ├── units.py
       │   └── users.py
       ├── editor.py
       ├── export_view.py
       ├── index.py
       ├── overview.py
       ├── terminology.py
       └── urls.py
   ```
   
   2.2 all in `core`:  
   
   ```
   ├── __init__.py
   ├── apps.py
   ├── core
   │   ├── forms
   │   ├── management
   │   │   └── commands
   │   ├── managers
   │   ├── middleware
   │   ├── migrations
   │   ├── models
   │   ├── templates
   │   ├── templatetags
   │   └── views
   │       ├── admin
   │       ├── api
   │       └── urls.py
   ├── dbs
   ├── i18n
   ├── locale
   ├── log
   ├── plugins
   ├── po
   ├── settings
   ├── settings.py
   └── static
   ```
   
   Expands to:
   
   ```
   .
   ├── __init__.py
   ├── apps.py
   ├── core
   │   ├── __init__.py
   │   ├── cache.py
   │   ├── checks.py
   │   ├── context_processors.py
   │   ├── decorators.py
   │   ├── exceptions.py
   │   ├── forms
   │   │   ├── captcha.py
   │   │   ├── fields.py
   │   │   ├── language.py
   │   │   ├── project.py
   │   │   ├── search.py
   │   │   ├── unit.py
   │   │   └── user.py
   │   ├── helpers.py
   │   ├── initdb.py
   │   ├── log.py
   │   ├── management
   │   │   ├── __init__.py
   │   │   └── commands
   │   ├── managers
   │   │   ├── __init__.py
   │   │   └── user.py
   │   ├── markup
   │   │   ├── __init__.py
   │   │   ├── fields.py
   │   │   ├── filters.py
   │   │   └── widgets.py
   │   ├── middleware
   │   │   ├── __init__.py
   │   │   ├── baseurl.py
   │   │   ├── cache.py
   │   │   ├── captcha.py
   │   │   ├── errorpages.py
   │   │   └── setlocale.py
   │   ├── migrations
   │   │   ├── 0001_initial.py
   │   │   ├── 0002_migration.py
   │   │   ├── 0003_migration.py
   │   │   └── __init__.py
   │   ├── mixins
   │   │   ├── __init__.py
   │   │   ├── dirtyfields.py
   │   │   └── treeitem.py
   │   ├── models
   │   │   ├── __init__.py
   │   │   ├── directory.py
   │   │   ├── language.py
   │   │   ├── permissions.py
   │   │   ├── project.py
   │   │   ├── quality_check.py
   │   │   ├── revision.py
   │   │   ├── scorelog.py
   │   │   ├── store.py
   │   │   ├── submission.py
   │   │   ├── suggestion.py
   │   │   ├── translation_project.py
   │   │   ├── unit.py
   │   │   ├── user.py
   │   │   └── virtualfolder.py
   │   ├── runner.py
   │   ├── stats.py
   │   ├── storage.py
   │   ├── templates
   │   │   ├── about.html
   │   │   ├── admin
   │   │   ├── browser
   │   │   ├── core
   │   │   ├── editor
   │   │   ├── errors
   │   │   ├── languages
   │   │   ├── layout.html
   │   │   ├── login.html
   │   │   ├── profiles
   │   │   ├── projects
   │   │   ├── staticpages
   │   │   ├── translation_projects
   │   │   ├── user
   │   │   └── welcome.html
   │   ├── templatetags
   │   │   ├── __init__.py
   │   │   ├── baseurl.py
   │   │   ├── cleanhtml.py
   │   │   ├── common.py
   │   │   ├── locale.py
   │   │   ├── render_pager.py
   │   │   ├── search.py
   │   │   ├── unit.py
   │   │   └── user.py
   │   ├── tmserver.py
   │   ├── url_helpers.py
   │   ├── utils
   │   │   ├── __init__.py
   │   │   ├── dateparse.py
   │   │   ├── templates.py
   │   │   ├── timezone.py
   │   │   └── wordcount.py
   │   ├── views
   │   │   ├── __init__.py
   │   │   ├── admin
   │   │   ├── api
   │   │   ├── editor.py
   │   │   ├── export_view.py
   │   │   ├── index.py
   │   │   ├── overview.py
   │   │   ├── terminology.py
   │   │   └── urls.py
   │   └── views.py
   ├── dbs
   ├── i18n
   ├── locale
   ├── log
   ├── plugins
   │   ├── __init__.py
   │   ├── contact
   │   ├── import_export
   │   ├── reports
   │   └── staticpages
   ├── po
   │   ├── terminology
   │   └── tutorial
   ├── settings
   ├── settings.py
   └── static
       ├── css
       ├── favicon.ico
       ├── images
       └── js
   ```

**Comment by julen** [comment]
Targeting future because this is not really urgent, and makes more sense to get to it once 2.7 is out. The proposed removals can perfectly be done at any time though.

Also, in order to get the ball rolling and not get stuck (bikeshedding etc.), let's try to identify points that everyone agrees on first, and only then focus/move on to points which might be subject to debate or result conflictive.

**Comment by unho** [comment]
Still didn't read the whole thing but I am leaving some quick comments.

@julen @dwaynebailey The reason why `pootle_notifications` and `pootle_autonotices` are still there is because *news* (notices) feels like a weird mixture of events timeline and instructions for users. If I remember correctly in @translate/house has been proposed long ago moving the instructions to announcements and move the events timeline thing to a new **Activity** tab. Since there is no programmatic way to tell if a notice is a timeline event or some instructions notice, no migration has been provided, thus the apps were kept. Probably the best approach is to throw all these away and reimplement from scratch if deemed necessary. If we are going to drop these I suggest doing it before 2.7.0 to carry less models in 2.6.0 upgrade.

**Comment by jleclanche** [comment]
Thanks julen, finally got time to review all this. Quick summary of my thoughts, in order:

* The pootle_ apps are absolutely not reusable.
* +1 on dropping notifications/autonotices. (cf. "why" vs. "why not", the app is not justifiable to me)
* +1 on everything that should be gathered in core *except* accounts (we can discuss that one later)
* I'm not familiar with terminology, can't comment.
* Imports look good but overall I'd like us to increase our usage of relative imports (from .models import ... instead of from pootle.models import ...)
* Some of our apps are massive. In order to move everything we will need to perform some serious cleanup and feature cutting or feature moving. Some *single files* in apps are over 2000 lines long!
* The plugin system is still up for debate. We were running with the idea before but with a proper model, it turns out to be fairly easy *not* to have plugins in master, as long as we provide the infrastructure for our users to modify pootle to their needs.
* I think it's a good occasion to review our settings layout. I heavily dislike it. Maybe I'm alone in this though.
* Your layout is confusing to read. Is this from root? From pootle/? If the latter, looks good overall, can bikeshed bits of it later.

**Comment by unho** [comment]
I like small steps. I suggest first moving stuff in `pootle_app` and `pootle_misc` to the definitive places. Maybe it is a good idea to merge `pootle_profile` and the `Permission` stuff from `pootle_app` into `accounts`. I suppose `evernote_auth` (not mentioned above) will be gone soon. Having less trees in the woods should help a bit.

I am reluctant to convert `core` into the place where all of our code lives. Previously `core` was the place for shared code that actually doesn't belong to any app, but I don't like the idea of moving the models, the views and everything there. I propose renaming `core` to `shared` and then move all the stuff in the apps to a new `core`.

Also I prefer extras to live within the repository. We can keep `apps` for now and then rename it to `plugins`.

I don't see anything about signals and signal handlers. In https://docs.djangoproject.com/en/1.7/topics/signals/ it recommends to put them in the `signals` module and connect them in the `ready()` method of the application configuration class. Right now we have them scattered across all the codebase.

Finally we need to rethink the whole terminology part. I still think that we should use `TerminologyStore` and `TermUnit` models and force people to use `TBX` or at least `CSV` instead of `PO`. Also, if things didn't change, the view to edit the terminology uses an old version of the translation editor. And I am not even going to insist on using a separate standalone app to manage the terminology because people looks like very reluctant to do it that way.

I like @jleclanche idea of doing something with big files. I am going to use the occasion to remember people about splitting models in `pootle_store` into separate files. In fact I like the idea of having `models` directory with a file for each single model. Maybe it is a good idea to do something similar for some views files.

I am not sure what is the problem with the current settings approach.

**Comment by dwaynebailey** [comment]
Some high level comments:

* autonotices and such. I need some way to comm to people, but I think the general agreement is that the News stuff really doesn't work well as is.  So I'm +1 to drop that and find another solution later.
* I've no particular preference for ``pootle.models`` vs ``pootle.core.models``.  I prefer the former because its shorter, the later because likely it leads to a less crowded root.
* Re terminology.  It has proved to be a very useful feature, even if its crusty.  It likely needs some love but I wouldn't want to see it go.  Losing the ability to autogenerate terminology would likely be a good thing.  So some paring down of what it does and cleaning up of how it does what we want is probably in order.  I'd prefer us not to dictate formats here.

**Comment by iafan** [comment]
@dwaynebailey: a side note on terminology: we do use this feature a lot, but maintain it outside Pootle (so for Pootle this is just another project that is marked as 'terminology'). YMMV, but it might be a pretty good balance between the feature usefulness and implementation+maintenance complexity.

**Comment by unho** [comment]
@translate/evernote @translate/house Is there any blocker for dropping now the items in "Should be completely removed" above?

**Comment by unho** [comment]
Another suggestion is to split API views to separate files, thus having a `views/` directory like we currently have for models or views in `pootle_app`.

**Comment by phlax** [comment]
i think this approach has been superceded
