### ISSUE TITLE
Import: errors not obviously visible, has coding artifacts and assumes too much from the user

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3666]
The following is the error generated after I had:

1. Successfully imported tutorial.po after offline editing
2. Then doing on one online edit to change a fuzzy to translated
3. Uploading the same file.
4. We expect this failure to occur.  That is good.

![screen shot 2015-04-09 at 13 08 49](https://cloud.githubusercontent.com/assets/647438/7066364/b3db9426-deb9-11e4-9d2a-905552603258.png)

The issues are these:

1. It is not obvious that the upload failed since the error occurs somewhere below.  We should use the message dialogs we use elsewhere in Pootle.
2. There are code artifacts in that we have ``u'tutorial.po'`` in the errors.
3.  The message is super confusing - a simpler error that describes what actually happened and what needs to be done by the user would be more useful.

  1. Could not create u'tutorial.po'. - we aren't creating we're uploading.
  2. Missing Project/Language? - we know that isn't the issue, why are we asking.
  3. (File u'tutorial.po' was rejected because its X-Pootle-Revision is too old.) - no translator will know that  X-Pootle-Revision is the issue.  Which really means that "Changes have been made on Pootle while you worked offline, the upload is being rejected to prevent those being overwritten.  Download the affected file again and resubmit your translations."

**Comment by dwaynebailey** [comment]
On second thoughts, part of this should be correctly fixed by making uploads with conflicts convert some things to suggestions.  Although that still needs a reportage.

**Comment by unho** [comment]
Just for the record, this comes from https://github.com/translate/pootle/blob/09dc4956/pootle/apps/import_export/utils.py#L41-L54

I think the problem is that even when we know that the X-Pootle-Revision is too old (see https://github.com/translate/pootle/blob/09dc4956/pootle/apps/import_export/utils.py#L46-L49) we are still mixing it with other message in https://github.com/translate/pootle/blob/09dc4956/pootle/apps/import_export/utils.py#L51-L54.

@jleclanche Any input on this?

**Comment by phlax** [comment]
issues raised here were dealt with a while ago
