### ISSUE TITLE
Pootle overwrites hidden strings at export from locamotion

### ISSUE THREAD

**Issue by kelemeng** [translate/pootle#3680]
I wanted to change some strings defining order of the first name and last name in Thunderbird on Locamotion. In the translated file they look like this:

```
<!-- LOCALIZATION NOTE:
 NameField1, NameField2, PhoneticField1, PhoneticField2
 those fields are either LN or FN depends on the target country.
 "FirstName" and "LastName" can be swapped for id to change the order
 but they should not be translated (same applied to phonetic id).
 Make sure the translation of label corresponds to the order of id.
-->
<!-- LOCALIZATION NOTE (NameField1.id) : DONT_TRANSLATE -->


<!ENTITY NameField1.id                  "FirstName">
<!-- LOCALIZATION NOTE (NameField2.id) : DONT_TRANSLATE -->
<!ENTITY NameField2.id                  "LastName">
<!-- LOCALIZATION NOTE (PhoneticField1.id) : DONT_TRANSLATE -->
<!ENTITY PhoneticField1.id              "PhoneticFirstName">
<!-- LOCALIZATION NOTE (PhoneticField2.id) : DONT_TRANSLATE -->
<!ENTITY PhoneticField2.id              "PhoneticLastName">
```

These strings are not exposed on Locamotion:
http://mozilla.locamotion.org/hu/thunderbird/translate/mail/chrome/messenger/addressbook/abCardOverlay.dtd.po#search=NameField&sfields=locations
http://mozilla.locamotion.org/hu/thunderbird/translate/mail/chrome/messenger/addressbook/abCardOverlay.dtd.po#search=PhoneticField&sfields=locations&unit=8645720

Now, I changed these manually in Mercurial:
http://hg.mozilla.org/releases/l10n/mozilla-aurora/hu/rev/55891ea53245
So NameField1 became LastName and NameField2 became FirstName - we use Easter name order, so this option is here for us Hungarians.
After that I changed some other strings in the same file, and Pootle overwrote my hand-committed changes:
http://hg.mozilla.org/releases/l10n/mozilla-aurora/hu/rev/b7704bed26c4

I'd like to be able to translate these strings on Pootle as well, or - if this is not feasible - expect Pootle to leave them alone.

**Comment by dwaynebailey** [comment]
Here are the issues:

1. Pootle will not see those strings as they are marked as DONT_TRANSLATE so they are not extracted i.e. not exposed in Pootle
2. When we create the .dtd file we use the en-US as a reference file which explains why these get overwritten.

Changing Pootle tools to know when programmers randomly want to things to be configured or not is I think too much of a task and the wrong approach here.

Reusing hu source files presents its own problem as we need to merge in en-US updates also.  This is maybe a process that a human could do but we can't automate that easily.  And not for such a small corner case.

The correct solution is to expose these in Pootle by getting the DONT_TRANSLATE tags removed.  I know they don't want these translated but they are configuration options that are exposed in many other places in Firefox and Thunderbird so that should be OK.

**Comment by julen** [comment]
Closing as this is not a Pootle-specific issue.
