### ISSUE TITLE
Language picker: Template language missing

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3711]
If we import a project with a ``templates/`` folder then that will not appear on the language picker.  If you browse into Templates by selecting the ``templates/`` folder then you get this broken UI:

![screen shot 2015-05-06 at 13 24 30](https://cloud.githubusercontent.com/assets/647438/7492759/45e84406-f3f3-11e4-8484-2fdf64f9715e.png)

1. The dropdown is missing
2. There is no text saying 'Templates'

**Comment by julen** [comment]
How is a `templates` folder within a project related to the language picker? I guess you mean the special `templates` language, which is intentionally left out.

**Comment by dwaynebailey** [comment]
@julen exactly that one

**Comment by julen** [comment]
@iafan do you recall the original motivation we decided to remove the *Templates* language? My understanding is we explicitly remove it because it results confusing to end-users, and at the time this was implemented non-empty languages were displayed as well — now languages with no projects are left out of this list, so it might be okay to remove this limitation.

**Comment by iafan** [comment]
I don't really remember if there was any discussion around this. Yes, looks like we can remove this limitation.
