### ISSUE TITLE
Prevent data loss on navigating away from the altered unit

### ISSUE THREAD

**Issue by iafan** [translate/pootle#3724]
We should show a modal confirmation dialog when navigating away from the unit with altered translation or fuzzy state (this includes loading another page, or clicking on another unit in the translation editor, or using keyboard to navigate away from the unit).

The dialog should read:

"You have unsaved changes in this unit. Navigating away from this unit will discard those changes."
[OK] [Cancel]

Pressing [OK] (or Enter) will discard the changes and continue navigation. Pressing [Cancel] (or Esc) will dismiss the popup and prevent navigation.

**Comment by julen** [comment]
There are different ways this could be implemented, but for the scenario where a new actual page needs to be loaded, the only approach is using the [`beforeunload` event](https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload), which would trigger a native browser dialog.

For the scenarios where users navigate away from the unit but still remain in the editor, any custom popup/markup/dialog can be used. So I wonder if we want to be consistent here and always use a browser dialog, rather than different types of dialogs based on the situation.
