### ISSUE TITLE
Generate help/_ttk_quality_checks.html on setup.py build

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3752]
The template is missing and causing a TemplateDoesNotExist on /help/quality-checks/.

According to @dwaynebailey there is a manage.py command to do that. Whatever that command does, it should be built upon setup.py build instead.

**Comment by dwaynebailey** [comment]
s/instead/as well/

**Comment by jleclanche** [comment]
I actually think it shouldn't be a manage.py command, it should just be a setup.py command.

**Comment by dwaynebailey** [comment]
The ttk version change needs to recreate that page, so running in setup.py is actually the wrong place for it.

The reality is that we should be building this from all available checkers as needed when ttk or pootle checks change.  We've got the ttk part right, just not the enchecker part.

**Comment by unho** [comment]
Yes, this should be included in the `setup` command in 2.7 (not in 2.6, since we are aiming at fresh install and final upgrade), but we don't have such command on 2.7. If we are not getting that `setup` command back, we can just include the step to rebuild the template in the installation and upgrade instructions. The command is `regenerate_checks_descriptions`.

**Comment by unho** [comment]
If the missing template is really a problem, then we can just add a blank template, and forget about what I said on my previous comment since rebuilding would be only necessary if TTK checks are enabled and TTK is upgraded.

**Comment by dwaynebailey** [comment]
@unho ``setup.py`` not ``setup``, please is such a minor irritation can we keep the noise down.  Just add it to the instructions if that is what was needed, it was your baby.

**Comment by unho** [comment]
Missing template added in 6008d341.
