### ISSUE TITLE
Get rid of `require_units()` method

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3782]
All long-running actions should be processed in RQ. We should prevent file parsing during `HttpRequest` handling that could happen because of  `require_units()`.
Let's return an empty list of units for unparsed stores.

**Comment by julen** [comment]
We have discussed this previously a few times and I'm adding it here FTR: ideally parsing should only happen explicitly on developer's request, otherwise it can end up being a unpredictable footgun; accessing `store.units` can trigger parsing anytime (including HTTP requests) without the developer noticing.

**Comment by phlax** [comment]
this is now gone! Removed in PR #4158
