### ISSUE TITLE
Deleting users should correctly shift attribution

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3797]
From IRC:

Dwayne: @julen if I delete a user on Pootle in the shell i.e. `u = User.objects.get(id=NN)` and then `u.delete()` does that do all the work of oving and contributions to 'nobody' user?

Julen: @dwaynebailey: nope, and the message in the UI is misleading as that hasn't been implemented in any case

**Comment by iafan** [comment]
When it comes to deleting users, do we always want to attribute everything to _nobody_? What's the primary use case for user deletion? I think one of the common cases for user deletion would be to clean up spam accounts, which means deleting user's suggestions (and reverting their changes) along with deleting the user itself.

**Comment by dwaynebailey** [comment]
These are my use cases:

- Delete - I'm doing cleanup of duplicate emails or users with no emails, etc and I don't want to lost any of their contributions
- Merge - this is the same user with different usernames, email.  I'd like to create one user out of the two
- Spam - I've never actually needed or wanted to do this to be honest.  But yes I can imagine a case where we want to revert all contributions.  But there is probably a software case, not of spam, but objectionable user or politically motivated suggestions.  Where you want to remove all pending suggestions from that person but you might not want to revert anything that was reviewed.

**Comment by iafan** [comment]
Thanks, @dwaynebailey 

So it looks like this boils down to two action items:

1. Proper user merging (because 'deleting' a user in the sense you describe actually means merging it with 'nobody', which would shift attributions). This will also give us arbitrary merging capabilities.
2. Wiping out the user (because of e.g. spam). In this case we will need to remove pending suggestions, and, probably, reverting active submissions to the prior state.

**Comment by unho** [comment]
Related #3810.

**Comment by phlax** [comment]
@dwaynebailey @iafan 

Currently when User.delete is called **all** related_objects are deleted - units, suggestions, submissions, etc

From the above comments I understand the changes to be:
 - On User.delete default to merging account with "nobody"
 - Have the ability to merge 2 arbitrary accounts
 - Have the ability to purge an account

I have added a commit to address this issue

It does the following:

  - Adds merge_user function to merge user's related_objects to other user
  - On User.delete() merge_user is called to merge to "nobody" account
  - Adds "purge" parameter to User.delete (default=False) to restore default behaviour
  - Adds merge_user and purge_user management commands
  - Adds tests to test User.delete, merging and purging

With this commit "purging" is basically the default django behaviour. It should be possible to have some kind of rollback purge where translations are rolled back to previous versions, but I wasnt sure if this was necessary so i havent added so far.

I will add docs for the 2 commands the have been added if you are happy with above.

**Comment by iafan** [comment]
@phlax, yes, when purging the user, we would ideally rollback translations to the previous state (when user's translations are the current one). Basically, we want to say: "this user never happened on this site and made no traces". I'm not sure what exactly the current (default) behavior is: we need to make sure it doesn't leave database in the incorrect state, where the user record is deleted, but his submissions/suggestions aren't.

**Comment by phlax** [comment]
@iafan the current default (which is django's delete behaviour) is to remove all related objects.

This means that all traces of the user are removed, but it also means that the units are removed rather than rolled back.

I can add the roll back functionality but its a bit more complex.

Im thinking that the rollback would:

- change translations to previous where user is listed as the last submitter
- remove pending and rejected suggestions
- reassign accepted suggestions to "nobody"
- remove comments

**Comment by iafan** [comment]
> set translation to "" if user is only submitter (or maybe delete unit)
You mean delete the submission, right? Not the unit?

> reassign accepted suggestions to "nobody"
why do we need that? I think simply removing any suggestions is ok (shouldn't leave db in an incorrect state).

I'd also want to hear from @julen and @ta2-1, since they better know the internals of the DB model.

**Comment by phlax** [comment]
@iafan 

>>    set translation to "" if user is only submitter (or maybe delete unit)

> You mean delete the submission, right? Not the unit?

Well - i meant the unit - on the basis that (eg uploading a translation file) the evil user might have added extra units - but i wasnt sure how safe this would be to delete.


>> reassign accepted suggestions to "nobody"

> why do we need that? 

cool - ill just remove the suggestions

**Comment by dwaynebailey** [comment]
> reassign accepted suggestions to "nobody"
> 
> why do we need that?

My logic would be that an accepted suggestion has at least been reviewed by someone else.  Unless of course the user accepted their own suggestion.  But if this is a true purge then I guess yes this is OK to remove.

**Comment by julen** [comment]
> * change translations to previous where user is listed as the last submitter
> * remove comments

Bear in mind the `Unit` model contains some denormalized fields which will also need to be adjusted: `submitted_by`, `submitted_on`, `commented_by`, `commented_on`, `reviewed_by`, `reviewed_on`.

Also, what will happen with the `revision` column?

> * set translation to "" if user is only submitter (or maybe delete unit)
> 
>     You mean delete the submission, right? Not the unit?
> 
> Well - i meant the unit - on the basis that (eg uploading a translation file) the evil user might have added extra units - but i wasnt sure how safe this would be to delete.

A unit will only want to be removed if it originated from the user being purged (which we are now able to detect thanks to #3744, right?). This never happens in our workflow for instance, because all units originate from `update_stores`, hence they're attributed to the *system* user.

**Comment by phlax** [comment]
> Also, what will happen with the revision column?

This is a good question - I would say it has to increment

> A unit will only want to be removed if it originated from the user being purged (which we are now able to detect thanks to #3744, right?).

@dwaynebailey and i were just discussing this as you typed it 8)

There are a few scenarios that need to be accommodated - unit has been reviewed, has suggestions, etc. It shouldnt be difficult to remove a unit that has no other history and was added by evil user in an upload.

**Comment by phlax** [comment]
This was fixed by #4002
