### ISSUE TITLE
Sign in issues in Firefox

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3799]
Forwarding from `#lxde`:

> [16:10:31] \<LStranger> I told you some time ago, you've probably forgotten. When I click on 'Sign in' I get a window which cannot be autofilled because button 'Sign in' is inactive until I actually enter a password manually. And when I add anything to autofilled password then delete entered (which is stupid at the least) it becomes active but clicking on it does nothing at all, that window can be only closed, nothing else happens.
> [16:12:09] \<LStranger> With chrome it at least lets me enter

**Comment by julen** [comment]
The problem is not all browsers fire a `change` event when the autofill mechanism is used ([Chrome is ok here, and Firefox too except for password fields](https://github.com/angular/angular.js/issues/1460#issuecomment-65494328)). Also, React doesn't seem to be making this uniform across browsers yet (facebook/react#1159).

There's [more in-depth info in a SO answer](http://stackoverflow.com/a/11710295). It seems that some hacky polling is the way to go unfortunately.

**Comment by jleclanche** [comment]
We could  *not* disable the sign in button, and prevent submission if the password is empty.

**Comment by julen** [comment]
Actually just tried the remember password + autofill feature in Firefox and it works well, so wondering if the actual issue being reported here is something else.

**Comment by jleclanche** [comment]
Seems he's running an old version of firefox. IMO we should prevent submission like I recommended in previous comment and call it a day.

**Comment by julen** [comment]
Version being? Notice we do not support old browser versions, [just latest stable](http://docs.translatehouse.org/projects/pootle/en/latest/developers/browsers.html).

**Comment by jleclanche** [comment]
24, but I still don't think disabling the sign in button is right.

**Comment by julen** [comment]
It's perfectly fine as there's no point in allowing to submit empty values. We also do this in other places, including legal page agreements or the editor. Marking invalid per the version comment.

**Comment by jleclanche** [comment]
@julen I disagree with the logic here. I dislike disabling the sign in button at all.
