### ISSUE TITLE
Vfolders name clashes with directory name

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3809]
After an extensive day of binary testing I managed to reduce the vfolder producing the error to this:

```json
[
    {
        "filters": {
            "files": [
                "dom/chrome/security/security.properties.po"
            ]
        },
        "is_browsable": true,
        "location": "/{LANG}/firefox/",
        "name": "security",
        "priority": 0.4
    }
]
```

The clash of names between ``security`` in the vfolder name and the directory seem to produce as dirty count of 6.  This doesn't seem to change with the addition of other files in that folder.

The problem disappears in a vfolder with 

```json
[
    {
        "filters": {
            "files": [
                "security/manager/chrome/pippki/pippki.properties.po"
            ]
        },
        "is_browsable": true,
        "location": "/{LANG}/firefox/",
        "name": "security",
        "priority": 0.4
    }
]
```

The same top level name of ``security``

There must be some component that I'm still missing as using the first example and calling the vfolder ``chrome`` doesn't seem to produce the same errors but by my theory they should since the names clash.

**Comment by unho** [comment]
Just as an explanation of what it is going on.

> ```json
> [
>     {
>         "filters": {
>             "files": [
>                 "dom/chrome/security/security.properties.po"
>             ]
>         },
>         "is_browsable": true,
>         "location": "/{LANG}/firefox/",
>         "name": "security",
>         "priority": 0.4
>     }
> ]
> ```

The previous JSON creates the following `VFolderCachedTreeItem`s for
`/af/firefox/`:

- `/af/firefox/security/dom/chrome/security/`
- `/af/firefox/security/dom/chrome/`
- `/af/firefox/security/dom/`
- `/af/firefox/security/`

The last `VFolderCachedTreeItem` is the problematic one, since it also exists
a regular directory with the same `pootle_path`.

> ```json
> [
>     {
>         "filters": {
>             "files": [
>                 "security/manager/chrome/pippki/pippki.properties.po"
>             ]
>         },
>         "is_browsable": true,
>         "location": "/{LANG}/firefox/",
>         "name": "security",
>         "priority": 0.4
>     }
> ]
> ```

The previous JSON creates the following `VFolderCachedTreeItem`s for
`/af/firefox/`:

- `/af/firefox/security/security/manager/chrome/pippki/`
- `/af/firefox/security/security/manager/chrome/`
- `/af/firefox/security/security/manager/`
- `/af/firefox/security/security/`
- `/af/firefox/security/`

Note that there is also a name clash here, despite @dwaynebailey says he didn't
suffer it.

**Comment by dwaynebailey** [comment]
@unho I know we talked about name clashes before. The spec calls for $vfolder-virtual in such cases.  But I thought we agreed that if there is a clash the vfolder would simply be disabled/ignored?

**Comment by unho** [comment]
@dwaynebailey Yes, see https://github.com/translate/pootle/issues/3534#issuecomment-101191057 and below.

**Comment by unho** [comment]
See #3905 for temporary workaround.

**Comment by unho** [comment]
Closing this in favor of #3534.
