### ISSUE TITLE
Mozilla Verbatim, google translation bug

### ISSUE THREAD

**Issue by SongHye** [translate/pootle#3820]
Hi! I'm S-Korean student. 
I've already done translating Pootle 2.7.0 at Pootle Demo(of course en->ko)
and I'm just join in Mozilla Verbatimㅡthe Mozilla localization project
(Mozilla Verbatim is runnung Pootle 2.5.0)
the top-right of the translation box(translating input box, ...), there's 3 buttons(tags, ...)
first button is Wikipedia(EN) and 
second is Google Translate (EN->KO) and 
last is copy in to translation.
'Google Translate (EN->KO)' does not work.
>>https://localize.mozilla.org/ko/spartacus/translate.html#filter=untranslated

whatever who use or not, if it doesn't work properly, I think it should be fix.

**Comment by dwaynebailey** [comment]
@SongHye thanks for the report.  We'll be upgrading that instance of Pootle to 2.7.0 shortly, so we won't likely address issues specific to Pootle 2.5.0 there for now.

In terms of Google, they've actually changed their terms of service so that feature won't work unless Mozilla actually pays for Machine Translation from Google.

So since this will go away shortly, I'm going to close this as an issue we won't fix on Verbatim.
