### ISSUE TITLE
Contact form: emails are not delivered to POOTLE_CONTACT_EMAIL

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3866]
That happened because `POOTLE_CONTACT_EMAIL` value is absent in `recipient_list` which is empty.

We tried to sent an email to `nobody`. And we don't raise any error in this case.
Default `recipient_list` is set by third `contact_form` app
https://github.com/ubernostrum/django-contact-form/blob/180676f5/contact_form/forms.py#L31
Contact form can work if `settings.MANAGERS` value is properly set.

`CONTACT_EMAIL` had been added to `MANAGERS`  before this https://github.com/translate/pootle/commit/a36f2df9#diff-8cf195c5c44454f6a88ef0e4560e0cc1L187

Let's overwrite `recipient_list` properly and raise exception if it's empty.

**Comment by unho** [comment]
This also affects the string error report feature.

**Comment by julen** [comment]
This is a regression introduced in 2eff228.

According to [Django docs on `settings.MANAGERS`](https://docs.djangoproject.com/en/1.7/ref/settings/#std:setting-MANAGERS), this setting has only effects when using [`BrokenLinkEmailsMiddleware`](https://docs.djangoproject.com/en/1.7/ref/middleware/#django.middleware.common.BrokenLinkEmailsMiddleware), which is not the case for a standard Pootle install.

Therefore, the actual issue would be django-contact-form redefining the semantics of `settings.MANAGERS`. Anyhow, since we already have our own email settings for both contact and error reporting forms with clearly defined meanings, we should use them directly by overriding `recipient_list` in each form as @ta2-1 suggests.

**Comment by julen** [comment]
@unho how is the error report feature affected by this? FWIW it already [overrides `recipient_list` with its own logic](https://github.com/translate/pootle/blob/master/pootle/apps/contact/forms.py#L73-L83).

**Comment by unho** [comment]
@julen For some reason the error report feature is not using `POOTLE_CONTACT_REPORT_EMAIL`. It should fallback to `POOTLE_CONTACT_EMAIL` but that is not working neither. I just override the contact form to use `POOTLE_CONTACT_EMAIL` and that works, but the report feature is still not using `POOTLE_CONTACT_REPORT_EMAIL` despite now works with `POOTLE_CONTACT_EMAIL`.

**Comment by julen** [comment]
Just checked and filed #3875 for that.
