### ISSUE TITLE
sync_stores --force is changing Last-Translator

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3924]
It seems that if you use ``sync_stores --force`` then we are updating the ``Last-Translator`` header entry.  Thus we're getting a lot of noise with only that field changing and nothing else.  It seems as if we're using the project last translator as apposed to the files last translator to populate that header entry.

**Comment by dwaynebailey** [comment]
This is a commit that seems to exhibit this issue https://github.com/translate/mozilla-l10n/commit/1cb922d9b8cc04a7944aef592308680f98a28763

**Comment by julen** [comment]
We went through this on IRC and concluded it's expected behavior.

First off, the original report was missing that the command is being run with `--overwrite`, which will account for **any** changes done to stores — this doesn't only include translations, but also metadata changes which can be reflected in headers.

The docs for `sync_stores --overwrite` were not accurate enough (as opposed to the CLI help), and that has been adjusted in 72c73cf.
