### ISSUE TITLE
Search options differ in translation project for terminology

### ISSUE THREAD

**Issue by iafan** [translate/pootle#3925]
When I go to any translation project for 'Terminology' project, the search form options differs from the standard one:

Terminology search options:
![terminology_search_options](https://cloud.githubusercontent.com/assets/1728158/8913867/86a01b70-3450-11e5-8446-7a6a3bf692e0.png)

Regular search options:
![regular_search_options](https://cloud.githubusercontent.com/assets/1728158/8913896/9ea66f12-3450-11e5-99e8-4365fbc162d5.png)

Since terminology is just another translation project, and units have the same properties, I don't see why the search options should differ. We need to have regular search options everywhere to avoid confusion.

**Comment by unho** [comment]
This should be the only place in Pootle where terminology is treated not as a translation format. I think this is the way is must be.

**Comment by iafan** [comment]
@unho, mind elaborating? For me this is quite confusing. Does the behavior of "Source Terms" differ from "Source Text"? What about "Target Terms" vs "Target Text"? "Definitions" vs "Locations"? What if one wants to search for comments provided along with source text?

**Comment by unho** [comment]
@iafan The way this is implemented (a terminology Store being the same as a translation Store):

- `Source Text` == `Source Terms`
- `Target Text` == `Target Terms`
- `Comment` == `Definition`

Note that `Location` has no equivalent for terminology.

I am curious about why it is used "Terms" in terminology search, since a `Unit` does not allow to have several translations at once for the same source, which is common in terminology, but makes no sense for terminology.

**Comment by iafan** [comment]
If the search behavior is the same, why we use different terminology for search options here? How does it help user to search more effectively? On the contrary, it would make them pause each time and think on how to search inside terminology.

Also, since terminology units come from .po (or other supported file formats), they technically do have a searchable location field.

So I'm inclined to unify the search options.

**Comment by unho** [comment]
> If the search behavior is the same, why we use different terminology for search options here? How does it help user to search more effectively? On the contrary, it would make them pause each time and think on how to search inside terminology.

I think the idea was to hide not valid options when searching terminology, thus helping the user to overthink. See next comment.

> Also, since terminology units come from .po (or other supported file formats), they technically do have a searchable location field.

Yes. But the location is completely useless for terminology.

> So I'm inclined to unify the search options.

Then you end up searching both on translations and terminology. I am not sure that is desirable when a user wants to specifically get terminology results.

**Comment by iafan** [comment]
> Yes. But the location is completely useless for terminology.

Not at all. It's just another searchable field. If someone provides reasonable data in this field, why not letting search by it?

> Then you end up searching both on translations and terminology. I am not sure that is desirable when a user wants to specifically get terminology results.

I believe this is what we already have. If we search for a term through all projects (and we have that UI), the results will be from all projects, including a terminology one. If one wants to search inside terminology, they would drill down into Terminology project and search there. Easy to understand, easy to explain.

**Comment by unho** [comment]
>> Yes. But the location is completely useless for terminology.
> 
> Not at all. It's just another searchable field. If someone provides reasonable data in this field, why not letting search by it?

Which kind of data? I can't think of any scenario where the location of a term is valuable.

>> Then you end up searching both on translations and terminology. I am not sure that is desirable when a user wants to specifically get terminology results.
> 
> I believe this is what we already have. If we search for a term through all projects (and we have that UI), the results will be from all projects, including a terminology one. If one wants to search inside terminology, they would drill down into Terminology project and search there. Easy to understand, easy to explain.

Just checked that you can't search for terminology outside a `terminology` project, and that within a `terminology` project you can't search for regular translations. IMHO a user should be able to search for terminology or translations everywhere. Perhaps there is no point on allowing to search for translations within the scope of a `terminology` project. But searching for terminology even in a project that has no `pootle-terminology.po` makes a lot of sense, since in that scenario it should fallback to a `terminology` project.

Or perhaps we should think that this is one of the symptoms of the of the larger problem on how terminology works on Pootle.

**Comment by iafan** [comment]
> I can't think of any scenario where the location of a term is valuable.

Since terminology can originally be managed in different files, the terminology extraction tool can provide location field to actually map units to the original files; we use location field to provide auto-generated metadata for units, and we want this to be searchable in any project in a uniform way.

> Just checked that you can't search for terminology outside a terminology project

I want terminology to be searchable when doing a global search. If this is not the case, then this is another consistency bug that needs to be fixed.

> and that within a terminology project you can't search for regular translations

This is correct and by design: search always works in the scope of the current sub-tree, so if you're inside any project, you can only search within that project.

> Or perhaps we should think that this is one of the symptoms of the of the larger problem on how terminology works on Pootle.

I don't see any problem with how terminology works in Pootle. We did a good job simplifying management/UI and making terminology just a regular project in terms of sync/browsing (and making search and navigation more consistent throughout the app). The only thing is that search UI differs for no good reason. My main point here is that _terminology projects are now regular projects_. So we want to treat them as regular projects in terms of UI. This is less code, less bugs, simpler UI and better UX.

**Comment by unho** [comment]
>> I can't think of any scenario where the location of a term is valuable.
>
> Since terminology can originally be managed in different files, the terminology extraction tool can provide location field to actually map units to the original files; we use location field to provide auto-generated metadata for units, and we want this to be searchable in any project in a uniform way.

How is relevant for terminology where it comes from? Terminology should be canonical on its own, and its origin must be completely irrelevant. Terminology is not like translation memory, where usually it matters where it comes from.

>> Just checked that you can't search for terminology outside a terminology project
>
> I want terminology to be searchable when doing a global search. If this is not the case, then this is another consistency bug that needs to be fixed.

I fully agree.

>> and that within a terminology project you can't search for regular translations
> 
> This is correct and by design: search always works in the scope of the current sub-tree, so if you're inside any project, you can only search within that project.

I agree. But if you merge terminology and translation search then it will be necessary to add some extra logic to retrieve terminology from terminology projects since now terminology projects are more or less treated like a regular translation project.

>> Or perhaps we should think that this is one of the symptoms of the of the larger problem on how terminology works on Pootle.
>
> I don't see any problem with how terminology works in Pootle. We did a good job simplifying management/UI and making terminology just a regular project in terms of sync/browsing (and making search and navigation more consistent throughout the app). The only thing is that search UI differs for no good reason. My main point here is that _terminology projects are now regular projects_. So we want to treat them as regular projects in terms of UI. This is less code, less bugs, simpler UI and better UX.

You seem to keep forgetting about having specific terminology for a project within it (`pootle-terminology.po` files). I do know that this is not a relevant scenario for you.

About *problem with how terminology works* I meant that there are some glitches on UI (you are able to edit a terminology project either using *Translate* or *Terminology*) and that the code needs to be reworked, most likely from scratch. I personally miss the ability to use external sources for terminology, lets say a static TBX file hosted on another server for example.

**Comment by iafan** [comment]
> How is relevant for terminology where it comes from?

Terminology is something that is managed by humans as well. It can contain typos, for example; translators might want to leave feedback on specific terms, and managers will need to find the term in a specific file to adjust it.

Note that I don't say "let's spend time implementing code for some edge cases". I say "let's simplify the code to make the UI more consistent and simple" (this is what this issue is about), and at the same time we will get the support for edge cases for free.

**Comment by unho** [comment]
>> How is relevant for terminology where it comes from?

> Terminology is something that is managed by humans as well. It can contain typos, for example; translators might want to leave feedback on specific terms, and managers will need to find the term in a specific file to adjust it.

Location in that search form stands for unit location. For example in PO this means the locations from where the translatable source was extracted from (file and line). But this is useless for terminology, despite I see you use them https://translate.evernote.com/eu/terminology_evernote/translate/#filter=incomplete&unit=4512390 By useless I mean that it doesn't matter where a term comes from (Firefox, LibreOffice or Evernote) since its definition already should contain any required context. And if you need to know where a specific terms is, for example for fixing a typo, searching it will open the editor which prominently displays the file where is the term. So there I don't see the need to search by location when it comes to terminology.

**Comment by iafan** [comment]
Yes, as you pointed out, we do fill in the location field and make use of it.

The search options UI needs to be unified disregarding how you or I use (or not use) that location field.

**Comment by julen** [comment]
> The only thing is that search UI differs for no good reason. My main point here is that terminology projects are now regular projects. So we want to treat them as regular projects in terms of UI. **This is less code, less bugs, simpler UI and better UX.**

We have been slowly moving away from special-casing terminology, and I see this as a step in that direction. Therefore I'd be happy to unify this UI across these scenarios (the outcome is :+1:).

**Comment by dwaynebailey** [comment]
My simple feedback on this would be similar to @julen's conclusion that is to not special case these things.  And I assume that was what @iafan is highlighting.  Summary: lets not special case Terminology.  It leads to more consitent UI, easier code with less special cases to maintain and/or fall over.
