### ISSUE TITLE
Use a single POOTLE_TM setting for all translation memories

### ISSUE THREAD

**Issue by unho** [translate/pootle#4086]
Using a single POOTLE_TM setting for all translation memories, external and local, would easily allow to configure all of them.

**Comment by julen** [comment]
Do you have any specific proposals here?

**Comment by dwaynebailey** [comment]
@unho I think this bug is premature, I don't think it refelcts what I'm after.  Lets first flesh the needed tasks out.  But single TM actually isn't the aim.  The aim is to bring back amagama as a TM provider in the POOTLE_TM_SERVER infrastructure and seperately to allow uploading other external TM resources in ES, but I wouldn't want them in the same instance.

**Comment by unho** [comment]
Closed since separate issues for local TM changes will be created.
