### ISSUE TITLE
Source string - some explanation needed

### ISSUE THREAD

**Issue by khagaroth** [translate/pootle#4107]
This string:
>In order to use the terminology feature, make sure to add to your translation project a "pootle-terminology" file named after your project's extension.

Could use some translator comment. It should note "pootle-terminology" is to be left verbatim (at least I deduced that from documentation). Also, the meaning of "named after your project's extension":one: is not obvious, there is nothing about that in the documentation, so it's hard to decipher the meaning.

:one: btw, it should be projects, not project's IMHO, though I'm not native English speaker so I can be wrong

Also, could someone disable the link for source error reporting that links to riseup pad, no one pays attention to it, so it only misleads users.

**Comment by dwaynebailey** [comment]
@khagaroth I'm at a little loss as to where you are seeing this and which links you are talking about.  Please can you add those to your report.  Also note that you can make changes to the Pootle docs and submit them as pull requests.  It helps having someone who hit the problem help the next person.

**Comment by khagaroth** [comment]
Well, the pootle demo translation server obviously http://pootle.locamotion.org/cs/pootle/translate/pootle.po#unit=1787915. The link is in the translation editor (the bug icon right top between search on wiki and copy source).
I can't make changes to docs, when I don't understand the function in the first place, that's why I asked for a comment from someone who actually knows what this means in the first place.

**Comment by dwaynebailey** [comment]
@khagaroth I've made the error link point to these github issues so that they won't get lost in future.  Thanks for reporting that.

And nothing is obvious, otherwise I wouldn't have asked for a link ;)  The link now makes it clear to us where the issue is located.

The string is really stating that the pootle-terminology files must be named as such and cannot be given another name.  And it would be pootle-terminology.po in a PO project.  Its a bit late for me to think clearly how to reword that or what comment to provide.  Now that you have some idea, suggestions are welcome

**Comment by khagaroth** [comment]
Thanks for the answer and changing the bug reports link.

So if I understand correctly it means that if it's a PO project it will be pootle-terminology.po and if it's XLIFF project it will be pootle-terminology.xlf?

So how about:
>In order to use the terminology feature, make sure to add a terminology file to your translation project. The terminology file must be named "pootle-terminology" and use the same file extension (format) as the rest of the project files.

**Comment by unho** [comment]
> So if I understand correctly it means that if it's a PO project it will be pootle-terminology.po and if it's XLIFF project it will be pootle-terminology.xlf?

In the PO scenario yes, but note that Pootle allows XLIFF projects with either `.xlf` or `.xliff` extensions, so for those it would be `pootle-terminology.xlf` or `pootle-terminology.xliff` depending on which extension (format) is the project set up to use.

>So how about:
>>In order to use the terminology feature, make sure to add a terminology file to your translation project. The terminology file must be named "pootle-terminology" and use the same file extension (format) as the rest of the project files.

Since someone found the original text to be confusing I would even go further and add an example afterwards:

> So a project that uses GNU Gettext should use a file named `pootle-terminology.po`. And a XLIFF project using the `xlf` extension should use a file named `pootle-terminology.xlf`.
