### ISSUE TITLE
Some update_tmserver flags and feedback are confusing

### ISSUE THREAD

**Issue by julen** [translate/pootle#4145]
I was trying the `update_tmserver` command and I found some confusing and counter-intuitive points:

1. Missing usage
 ```bash
$ ./manage.py update_tmserver
CommandError: Specified Translation Memory is not defined in POOTLE_TM_SERVER.
```
 At this point the users are lost, as they didn't specify any TM yet it complains about the specified TM not being defined in `POOTLE_TM_SERVER`. At the same time, they have absolutely no clue what `POOTLE_TM_SERVER` is. Since this returns a `CommandError`, users might think they're doing something wrong when typing the command in, however the complain is about settings.

2. `--project` is ambiguous and confusing
 ```
$ ./manage.py update_tmserver --tm=default foo.po
CommandError: You must specify a project with --project.
```
 The naming is confusing, as one can think this has to be a project existing in Pootle, which is not the case. If it's a label or display name, let's rather use something along those lines, as `--project` is ambiguous in this context.

3. Incomplete usage message
 ```
$ ./manage.py update_tmserver --help
Usage: ./manage.py update_tmserver [options]
...
```
 Among other things, nowhere in the CLI is defined that one can pass file paths as arguments to the command.

**Comment by unho** [comment]
Thanks a lot for your review.

> 1. Missing usage
```bash
$ ./manage.py update_tmserver
CommandError: Specified Translation Memory is not defined in POOTLE_TM_SERVER.
```
 > At this point the users are lost, as they didn't specify any TM yet it complains about the specified TM not being defined in `POOTLE_TM_SERVER`. At the same time, they have absolutely no clue what `POOTLE_TM_SERVER` is. Since this returns a `CommandError`, users might think they're doing something wrong when typing the command in, however the complain is about settings.

This happens because the user did not rename `default` TM server to `local`. Since `--tm` is not used, it defaults to `local`, but since that TM is missing on settings this error is thrown.

The message can be reworded like *CommandError: Translation Memory 'local' is missing in settings*. Will PR the change so people can give their opinion there.


> 2. `--project` is ambiguous and confusing
```
$ ./manage.py update_tmserver --tm=default foo.po
CommandError: You must specify a project with --project.
```
> The naming is confusing, as one can think this has to be a project existing in Pootle, which is not the case. If it's a label or display name, let's rather use something along those lines, as `--project` is ambiguous in this context.

I agree this might be confusing. Using `--display-name` or `--label` doesn't looks very self-explanatory, forcing users to check the help, so perhaps that is a better way. I am going to create a PR renaming it to `--display-name`.

> 3. Incomplete usage message
```
$ ./manage.py update_tmserver --help
Usage: ./manage.py update_tmserver [options]
...
```
 > Among other things, nowhere in the CLI is defined that one can pass file paths as arguments to the command.

Yes, needs fixing. Tried to specify an `usage` variable in the command, but for some reason is failing.

**Comment by unho** [comment]
See #4147 for proposed fixes.
