### ISSUE TITLE
Modify outbound email headers to prevent mail from being bounced

### ISSUE THREAD

**Issue by iafan** [translate/pootle#4176]
We currently use `From: "{{user.display_name}}" <{{user.email}}>` header in the emails we send from Pootle. This doesn't work with all servers. For example, it doesn't work with Yahoo emails as their server bounces our emails with the following error message: `Unauthenticated email from yahoo.com is not accepted due to domain's 550-5.7.1 DMARC policy.`

So let's make sure all outbound emails have the following `From:` and `Reply-to:` headers:

```
From: "{{user.display_name}}" <{{settings.DEFAULT_FROM_EMAIL}}>
Reply-to: "{{user.display_name}}" <{{user.email}}>
```

**Comment by julen** [comment]
Note that in order to send emails this way, it'd be necessary to patch/replace the contact form package, as it's using Django's [`send_mail()`](https://docs.djangoproject.com/en/1.7/topics/email/#send-mail) function, and this works fine for most of the cases but it lacks the ability to specify advanced features such as extra headers.

**Comment by iafan** [comment]
@phlax, @julen: with this fix, do we need to do anything else in the code/templates to make sure this works across all the emails that Pootle sends out?

**Comment by phlax** [comment]
@iafan this fix is specifically for emails sent out from the contact form - it wont affect any other emails - but as i understand these were the only ones affected

**Comment by julen** [comment]
Reopening since we noticed the change includes just the email address, and the full name is missing in the headers.
