### ISSUE TITLE
Make Markdown the default content format

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4184]
At the moment we fall back to HTML for `POOTLE_MARKUP_FILTER`.  This seems like a safe default but means that most people then are required to write HTML and might not even know that they can use simpler Markdown if they configure things.

I'd like us to change this so that:
1. Markdown is the default and is installed by default.
2.  Choosing HTML is a concious decision.

This would mean that the default is sane and simple for anyone writing pages.  You do lose complete control, and that's for the HTML people, but you gain a very simple way of adding pages.

**Comment by dwaynebailey** [comment]
@translate/evernote can we have some thoughts on this?

**Comment by julen** [comment]
I totally love markdown. Having said that, I believe HTML is a saner default because:
* It's more widespread than other markup formats, and more people are familiar with it.
* It requires no extra dependencies.

> people then are required to write HTML and might not even know that they can use simpler Markdown if they configure things

Arguably the same can be said about any default markup format. Is discoverability perhaps the real issue?

cc @iafan for extra thoughts.

**Comment by phlax** [comment]
@julen i think the problem is that atm users are by default encouraged to edit html in a non-html editor - which even for experienced coders can be a pita. Although  i can definitely understand the reasoning to offer html input.

Having markdown as the default seems to offer the right balance of user-editability

**Comment by julen** [comment]
The editor highlights the markup mode you are on and the live preview is immediate (this is even an extra advantage for HTML as it requires no server round-trips). This has been a recent improvement; did you miss this feature perhaps?

**Comment by phlax** [comment]
no i see that - but im still not that keen on editing HTML outside my editor - and generally against asking end users to edit it without an WYSIWYG editor

**Comment by iafan** [comment]
Can we probably use both at the same time? Markdown itself allows for inline HTML. We could use Markdown by default, seamlessly adding HTML tags and CSS styles as they need them.

With that being said (and if everyone agrees that this is something we'd like to explore), I'd suggest the following:

1. Make Markdown->HTML conversion in JavaScript, to make sure there's no round-trip to the server during the preview.
2. Make this conversion always on (so that both `None` and `markdown` values for `POOTLE_MARKUP_FILTER`) work the same; marking one of those as obsolete. This will give a good config upgrade path.

**Comment by iafan** [comment]
With that, we might also want to discontinue the support for `restructuredtext` option.

**Comment by unho** [comment]
And also drop `textile`.

**Comment by julen** [comment]
Both at the same time might be a good compromise: [check a working example](http://jonschlinkert.github.io/remarkable/demo/).

If along with this the rest of the options are gone (reST, Textile), I can foresee extra benefits:
* Zero configuration and sane defaults, hence no extra docs or discoverability issues
* No need for custom `MarkupField` (the rendered contents are directly stored in the DB)
* Instant preview always (no need for custom XHR endpoints for round-tripping)
* Simpler front-end code for the CodeMirror editor component.

An open question would remain for transitioning over from reST and Textile — however [we already questioned](https://github.com/translate/pootle/issues/4111) whether they were actually being used or not. If there's no intention for an abrupt change, it'd be wise to warn deployments that `POOTLE_MARKUP_FILTER` is being deprecated in version N, then removed in N+1.
