### ISSUE TITLE
Stats: clear and handle dirty counts in refresh_stats command

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4219]
If we have dirty items it can mean:

1. the stats are being calculated, in case there are pending jobs;
2. the stats calculation didn't complete successfully, in case there are failed jobs;
3. there was some other issue with the worker, in case there are no pending/failed jobs;

How these dirty items can disappear?

1. automatically after pending jobs are finished;
2. after admin run `retry_failed_jobs` command;
3. after dirty stats are removed manually;

Sometimes `retry_failed_jobs` command can be useless in 2nd case. Jobs can be failed again and again. 

How to handle with dirty items? We can describe some things in #4216.
But we can expect to have no dirty stats after running of `refresh_stats` command.

Let's think how we can safely remove all dirty flags before refresh.
`redis-cli del pootle:dirty:treeitems` can be added in the beginning of `refresh_stats` in the simplest case when we refresh all stats but it can be run if there are no pending tasks and `rqworker` is stopped.

**Comment by unho** [comment]
`refresh_stats` is not necessarily going to be run at top level (no arguments) but instead we usually pass a language and project thus restricting it to a specific TP.

So in our regular scenario `refresh_stats` should remove the dirty counts for the path where it is being run before it calculates the new stats from scratch. In this approach `refresh_stats` should be able to get rid of those dirty counts without stopping any `rqworker` if it manages to prevent any other job to be run for that path.

This new behavior (remove dirty counts) should be added to `clear_stats`. This command will be less necessary though but IMHO we should keep it since it provides an easy way to remove all the stats.

**Comment by iafan** [comment]
@ta2-1, would you mind explaining this in a bit more detail?

Am I right that what you want to do is to recover (clear) the dirty state after the job has failed? But if the job has failed, the stats are incorrect by definition, so clearing the 'dirty' state will just hide the error, not fix it. Am I missing something?

**Comment by ta2-1** [comment]
@iafan, I'm talking about refreshing of stats, because we can add new jobs and refresh stats but dirty items will stay. So refresh_stats won't work as we expect. 
Speaking about `clear_stats` command, it was to clean not dirty items only but remove all stats values. And I think that it can make sense as a first step before refreshing of stats.

**Comment by iafan** [comment]
The question is "why dirty items will stay after successful `refresh_stats`?". Let's discuss later today,

**Comment by unho** [comment]
> The question is "why dirty items will stay after successful `refresh_stats`?". Let's discuss later today.

After a successful `refresh_stats` there might be dirty items because there is some other `refresh_stats` being run yet. Think for example on two `refresh_stats` for different TPs for the same language.

**Comment by iafan** [comment]
@unho, there's no problem with this scenario. The problem is that we do not recover the sate of the dirty counts after job failure. And my understanding is that we need to focus on why jobs fail rather than trying to clean up the dirty counters as a part of the normal `refresh_stats` routine.

**Comment by dwaynebailey** [comment]
@iafan yes that is ideal.  But I think the general concern would be:

1. You get some stats count error
2. You fix it
3. You can never fix your stats counts unless you ratchet up your redis skills as we can never get rid of the dirty counts, failed jobs, etc.

That's my understanding of this problem.  And while its great to want to address the core issue.  Its not great to have it be really really hard to clean up.

**Comment by iafan** [comment]
@dwaynebailey, thanks for summarizing this. I guess the only point I want to raise is that I would prefer us not to "auto-fix" the dirty counters somehow (because it may be harder to find and fix the original stats counting issues). Of course there can be a special maintenance command that will do the Redis db cleanup.

**Comment by ta2-1** [comment]
`flush_cache` command was added in #4319. Use `flush_cache --stats` to clear all stats with dirty counts.
