### ISSUE TITLE
[Regression] Language codes below TPs are case-sensitive

### ISSUE THREAD

**Issue by julen** [translate/pootle#4373]
Case insensitivity in language codes has regressed when accessing translation projects as reported by our L10N managers.

While from the user perspective both `/pt_BR/` and `/pt_br/` work and point to the same location, accessing a translation project produces inconsistent results: `/pt_BR/<project_code>/` is accessible, whereas `/pt_br/<project_code>/` is not.
*(For the sake of completeness, the actual case for the language code in the server is `pt_BR`)*

This can be reproduced in EN's production server:
* https://translate.evernote.com/pt_BR/
* https://translate.evernote.com/pt_br/
* https://translate.evernote.com/pt_BR/corenote_evernote/
* https://translate.evernote.com/pt_br/corenote_evernote/ **(404)**

While the previous behavior can be reproduced in MLO:
* https://mozilla.locamotion.org/pt_BR/
* https://mozilla.locamotion.org/pt_br/
* https://mozilla.locamotion.org/pt_BR/terminology/
* https://mozilla.locamotion.org/pt_br/terminology/

Accessing resources under the lowercase language code also suffers from this issue.

**Comment by iafan** [comment]
I know that the fix (for the regression) has already landed, but I would like to propose an improvement: it would be nice if we could redirect to the canonical URL instead of just serving the page under a non-canonical one. In other words, if someone goes to `https://translate.evernote.com/pt_br/whatever` they would be redirected to `https://translate.evernote.com/pt_BR/whatever` with 'Redirected permanently' status. This will make sure people don't share non-canonical URLs.

**Comment by phlax** [comment]
@iafan that sound like a good idea to me - ive opened a separate bug for it #4381

**Comment by julen** [comment]
Reopening as this now produces a `No Directory matches the given query.` error.

**Comment by phlax** [comment]
@julen can you provide a bit more information - this appears to work for the urls im testing - how have you triggered this error?

**Comment by julen** [comment]
Just accessing any TP or TP resource with the lower cased version of the language code triggers this. I double-checked I'm running the right code. Our staging server also exhibits the same (runs master).
