### ISSUE TITLE
calculate_checks requires running refresh_stats afterwards

### ISSUE THREAD

**Issue by unho** [translate/pootle#4482]
If you run `calculate_checks` you will have to also run `refresh_stats` afterwards in order for the detected critical errors to be shown on the stats. This is necessary since if no errors are detected in the stats no links are properly rendered to directly see the errors in the editor.

Documentation says that `calculate_checks` **will flush existing caches and update the quality checks cache**, so probably the right fix is to align `calculate_checks` behavior with that statement.

**Comment by unho** [comment]
@translate/core Other way to handle this is to remove that phrase from docs and instead warn about that it is necessary to run `refresh_stats`, and also adjust `calculate_checks` to output this message after being run.

**Comment by phlax** [comment]
as @dwaynebailey has mentioned - as calculate_checks makes the stats out-of-date - it makes sense that it should happen automatically.

However, my only concern is that a sysadmin/dev should also have the possibility to run only calculate_checks if they wish to - as both calculate_checks and refresh_stats are resource-intensive and take a while.

**Comment by dwaynebailey** [comment]
Having to run `refresh_stats` manually and documenting it as such is at best a band-aid or temporary fix.  

As an admin I'd be running `calculate_checks` because I need to update a changed check.  I'd expect that to mean that data on the front end gets updated.  Having to do it manually is not logical to me. Also, in a large project, you're updating a lot of data, most of which does not need updating.  While `caclulate_checks` is in a better position to know exactly which data should be updated.

**Comment by ta2-1** [comment]
I've referenced this issue here https://github.com/translate/pootle/commit/16b607580795631eee96e9ba8043c2af42cd046e.

`refresh_stats` triggers jobs for all stores and updates all stats data.
`recalculate_checks` can trigger stats updating for checks data only and for those stores that are changed.
I think we need to fix `calculate_checks`.
