### ISSUE TITLE
Export user list to a CSV file

### ISSUE THREAD

**Issue by leuce** [translate/pootle#459]
At present, the only way to see the users (user name and real name) of the Pootle server is to view all of them in an HTML page.  The page takes a long time to load.  In addition, the page contains very little useful information, but I suspect adding more information would increase the load time.

RFE:  Make it possible for an admin user to let Pootle export the user list as a CSV file, to download.  A bonus might be to automatically zip the CSV file, to reduce download time and to prevent misconfigured browsers from rendering/displaying the file while downloading it.

RFE II:  Include other information on this CSV file, such as which projects and which languages the users are listed under, and optionally also what their permissions are (abbreviated, perhaps).

**Comment by gingerling** [comment]
so this feature is now available?

**Comment by julen** [comment]
Nope @gingerling, @jleclanche closed your issue as a duplicate of this one.

And talking about this, I'd advise against the feature being considered for Pootle: it's a very specific request, it's not clear what problem this actually solves (note we have a new admin UI), and a custom management command can do this type of specific exporting and more.

**Comment by jleclanche** [comment]
@julen I agree. It's simple enough for our users to write a script that exports the accounts_user table. If it becomes a popular request we can always document it or provide an external script. Thoughts @dwaynebailey ?

**Comment by dwaynebailey** [comment]
@jleclanche I agree with @julen especially as we now have a new admin UI and I'd rather see if that addresses the need first.

**Comment by gingerling** [comment]
The problems I have, as a community manager, is finding out:

1) who our active translation community
2) who is doing what within that community
3) linking that to the name, emails etc

In the phpList community, the developers (using mantis, phpBB and github) and documenters (using flossmanuals and wordpress) who have been active since the last release of phpList get thanked in the blog which launches the next release. 

In all four of the software's we use for that, I can see who has been active and what they did then get their email to arrange the thank you note. I have been unable to do this in pootle and this is resulting in the translation community being excluded from the thank you notes in the blog etc. 

This specific bug report was made a while ago, and obviously does not reflect the scale of the problem: we have been trying to address this internally with scripts etc  we have made almost no progress.

**Comment by jleclanche** [comment]
@gingerling I think you'll like the new score system that is coming in 2.7.0. We have several new ways to display and thank contributors which we didn't previously focus on.

**Comment by gingerling** [comment]
it sounds good. How long till 2.7?

**Comment by jleclanche** [comment]
No ETA yet, hopefully within a couple of months.

**Comment by dwaynebailey** [comment]
@gingerling you can follow the 2.7.0 milestone and we expect to deploy some instances before an official release.

**Comment by jleclanche** [comment]
wontfix.

**Comment by gingerling** [comment]
@jleclanche you mention a new score system in 2.7 which could solve some of my issues. Did this happen? I can't find much about it. Is there an up-to-date demo anywhere?

**Comment by jleclanche** [comment]
The scoring system is in 2.7 yes, scores are available on the index.

**Comment by gingerling** [comment]
Can you send me a screenshot, so I can see what it's like. I need to try and assess if it solves the problem or if I need to make a feature request
