### ISSUE TITLE
Translation editor leaks memory

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4603]
If you use the translation editor while profiling you will see the node count increase, and the number of event listeners on the window.resize object also increase.

This is because autosize is inited repeatedly without destroying the previous event handlers.

The knock-on effect is that as autosize maintains a ref to the old elements, the elements' ref count never zeros and the elements are not garbage collected. It also multiplies the event handlers on the window object slowing the editor down.

I have a fix which:
- prevents autosize initing on uneditable textareas
- destroys the event handlers before removing the target dom elements

**Comment by iafan** [comment]
@phlax also FYI: https://github.com/jackmoore/autosize/issues/270. It was fixed in autosize 3.0.14, though we still require ^3.0.6, and the way `^` works may lead to servers still using a pretty old version of the component (I just checked our own production server, and it has 3.0.12). I already asked @julen to bump up the version to the latest one in `package.json`.
