### ISSUE TITLE
Integrate existing command to generate invoices

### ISSUE THREAD

**Issue by julen** [translate/pootle#4619]
At Evernote we have developed and have been actively using an invoicing solution integrated with Pootle, which with the help of the existing reporting code in Pootle, allows deployments to generate HTML and PDF invoices and have them sent via e-mail.

We believe this can be beneficial for any Pootle instance running in a context similar to ours (with paid translators and/or agencies involved), and we are happy to make this code available for everyone, including the necessary instructions and documentation.

At first we thought we could make a separate package out of it, although after checking how reports currently work internally, it'd be best to merge this in Pootle. This way anyone in a situation like ours can start using invoicing features right away. We are happy to look towards decoupling both reporting and invoicing features in the future, though.

We'd love to get a :+1: before creating a PR for this.

**Comment by unho** [comment]
I don't oppose. Perhaps other people are not happy with the idea. In any case I would like the reports/invoicing feature to be disabled by default if possible.

**Comment by phlax** [comment]
I would really rather this did not land in core pootle, for the following reasons:

- i dont know of any other users that will use this feature
- we havent finished fixing the many serious security holes that have already been identified in related code
- my feeling is that Pootle should be a translation editor and just that
- users installing Pootle do not generally expect to install an ERP, time-tracking or other similar types of software - they usually just expect that they are installing a translation editor
- we are already unbundling parts of the code that are not used by all users to make it easier to create addons/plugins - and to my mind this is where this type of feature should live
- adding a feature that noone else uses puts a burden on core developers in terms of auditing/testing/compatibility/releasing/documentation etc/etc that really has little to do with translation

**Comment by julen** [comment]
I totally agree that Pootle should be _just_ a translation editor and its core kept thin, and I already expressed that a few times elsewhere.

Without ignoring that Pootle deployments available out there respond to different needs, let us mention the fact that we have been approached by several companies interested to learn more about our integrated reporting and invoicing solution.

The piece we are offering to bring in here is a management command only (plus docs and tests). It doesn't affect any feature per-se, it doesn't affect performance, it doesn't get in the way, but it makes the **existing** report-related code actually useful: should you need it, you'd have the chance to use the command to generate invoices.

I realize my choice of words for _feature_ has rather given the wrong impression, as if it was a heavy feature on its own. My apologies for that.

And just to reiterate it, we are happy to look towards unbundling this code from Pootle, although considering that decoupling it is nowhere a simple task achievable in the short term, especially given the lack of resources to prioritize it, we want to make it clear we will be actively maintaining it — this should be no news, as we absolutely rely on this feature in production. In this regards, one intermediate option might be what @unho suggested, making reports disabled by default behind a flag, so at least initially it doesn't show up in the UI.

**Comment by phlax** [comment]
i would really rather that more non-translation editor cruft is not added *before* this stuff is unbundled - as i said already - i dont think its fair on us as developers who have neither interest nor knowledge in any of this functionality, nor on users who are really not expecting to install all of this when they install a translation editor

**Comment by iafan** [comment]
Users who don't need any of the paid functionality won't be affected at all (and probably will not even notice this), so this seems to be an overreaction. Corporate users who actually need to work with paid translators will be able to finally count Pootle as a fully working solution (and I personally will be able to advertise it as such to people who ask us about out translation solution). I think this outweighs hypothetical problems the code could bring in the short term. This command will actually complete the existing (and pretty important to the future of Pootle, I believe) functionality rather than add a new one.

I would like everyone here to be realistic, and would also like to hear from @dwaynebailey and @ta2-1

**Comment by ta2-1** [comment]
IMHO:
- this functionality (https://mozilla.locamotion.org/user/SYANI/stats/) is important for every client;
- it should be enabled by default (users can disable or protect with password if they need it). I'd suggest to have all available functionality just out of the box. I think it is easier to remove unnecessary plugins than to add them.
- there are some parts (`PaidTasks` ) that can be confusing but they are already in the core;
- we can consider current reports app as a part of big reporting framework in future;
- decoupling from the core is a right way of development;
- we need to discuss plugin infrastructure all together (technical things and either how to advertise all related pootle stuff);
- invoices is a small part that is very coupled with reports (which currently is core). 

I believe we can rely on @julen who wants to support it. there are no difference if we decouple pootle and reports with invoices or pootle and reports without invoices. So it is not fair to push it back before we are able to find resources and get some agreements re plugin infrastructure. 
I'd stress that we shouldn't add new "unnecessary" features to core but we shouldn't block development of existing things.

**Comment by dwaynebailey** [comment]
@julen asked me to raise politics here.  Apart from being slightly upset that genuine concerns about maintainability of the software are seen as politics.  Lets me try restate the concerns I have that still remain unchanged.

1. This really should be a plugin.  We agreed in Zurich to do that and we all know why this is an advantage.  We have the very best candidate we've ever had. It isn't that together we've chosen not to do this as a plugin, it's essentially being forced onto the Pootle devs.  For that I'm lost.  And that central issue really feeds into all the other concerns.
2. This does increase maintenance issues.  Supporting people on the channel, fixing docs, landing code that impacts invoices.  All those increase maintenance not matter how you slice it.
3. It really isn't a core feature.  Yes its useful.  Yes others might find it useful. But even if I had paying support contracts for this aspect I'd still be talking plugin simply because of the ability to safely maintain the code.
4. Pootle has had some pretty dramatic cleanups.  Code coverage is high enough now that for the first time I feel like we can actually make big changes without breaking things.  We've fixed and removed security issues, massive performance bottlenecks. Generally I think we've had to work really really hard to bring Pootle forward where the code is in a much better shape.  Now I'm not saying the code landing is bad code.  But nobody has or can really review it.  So in effect landing this very specific code just helps us lose all that we've gained.  Our biggest risk is that we have a new lump of code that had to be modified when we move to Django 1.9, that has security issues that impact all users, that has bugs that need fixing and cleanup.

I've stayed quite quiet on this as I was hoping that enough pushback would lead to some reason, and not what I'm seeing which is a simple push without addressing some of the major concerns.

We've had some pretty hardcore pushback on issues that had serious security considerations.  We've had to justify things with reams of performance data. We've had to argue for security and performance over lost functionality.  And when we've pushed we've worked worked hard to provide technical reasons.  Our experience on mlo has vindicated us tbh. The server is stable and not eating the resources it did before.  Sure there are technical issues that still need cleanup.

But I'd really prefer to be seeing this move forward like that.  I'd really love to hear some real technical reasons as to why this isn't a plugin. AFAIKT that would address all of the other concerns, still mean that code is out there and used, and still mean its maintainable by others.  We get the benefits without the associated risks.

I'd like to know how we get from a code dump that nobody is really able to review or test (time, expertise and other priorities).  To a plugin that people can start to use, test and improve.  A plugin that is part of Pootle but doesn't bring associated risks.

**Comment by iafan** [comment]
The idea of this commit was to fix the existing functionality (make it feature-complete), not externalize the existing code. We all agreed to that moving the payment-related functionality into a plugin would be a natural move, but this is beyond the original scope of this specific PR, as this paid functionality is not that easy to decouple from other features that piggyback on it, and it requires some thoughtful approach in order not to break or complicate things further.

The code in this PR is developed by one of the core Pootle devs, it is tested, it is actively used, it contains documentation and test coverage, so I'm not really buying the reasoning that it degrades maintainability.

If you prefer, we will not land it (it's your final call), which will simply leave the current paid functionality in an incomplete state in the current product and actually with less documentation and less test coverage (so this will be quite the opposite to what you're trying to achieve).

**Comment by dwaynebailey** [comment]
@iafan I think a number of us have told you exactly what we would prefer, a plugin.  While that might not have been your goal with this PR I think we've been at pains to explain that we think it's the correct approach.   Even @julen expressed it as being the right approach. And it feels terribly like we're not being heard.  I'm not asking this not to land, I am asking that it not land like this.

I'm really not sure why there is simply no engagement on the plugin angle.  Are resources an issue? If so then please say so instead of us having to have a meta conversation about this.

There is more than one person who needs to maintain, fix and debug this code.  If that one person is only Julian, then yes this is a maintenance risk.

I would really love this conversation to be about how we can land invoices in a way that works for everyone. So can we please avoid rhetoric that sounds like "take it or leave it" or about making something "feature complete".  We want a good outcome as much as you, but I'm not happy to be strong armed with reasoning that is not technical.

I can think of a few ways forward, but tbh if we're not having a conversation that is driving towards a solution then I'm not 100% sure it's worth raising them.  Please show that I'm wrong and lets generate some alternatives.

**Comment by dwaynebailey** [comment]
@iafan I deleted my followon comment.  Can we voice?

**Comment by iafan** [comment]
> I'm really not sure why there is simply no engagement on the plugin angle. Are resources an issue? If so then please say so instead of us having to have a meta conversation about this.

I believe we were pretty clear about this, and expressed our position multiple times. We wanted to fix (complete) the currently existing functionality and provide more tests/documentation in order to improve the coverage _before_ we start working on a plugin. Yes, making this a proper plugin requires much more resources and we do have some priority things to finish before we can work on it. Yes, we wanted to make sure everybody agrees on how to make this a proper plugin _before_ we start implementing it. This will not only require more Julen's resources, but also more of your team's resources/time. I don't want to have two teams implementing their own plugin approaches, and there was never a public conversation (a systematic approach to plugins), unfortunately.

So we genuinely thought that this PR would be a proper first step in order to improve the already existing situation, have the entire feature in the codebase along with its documentation/tests for everybody to understand what this feature is about before we sit together and see how this all can be externalized correctly and whether it will require some infrastructure on the core side.

**Comment by julen** [comment]
> see how this all can be externalized correctly and whether it will require some infrastructure on the core side.

To get into specifics of this matter, I went through the code to identify what needs to be done _before_ this can be made a plugin on its own, and #4725 has been filed for that. Check that out for details/discussion on the matter.

I suggest as a way forward we should:
* Merge #4648
* Provide the mechanisms so that the necessary components can be externalized
* Externalize the reporting and invoicing code

In case this results concerning, please note that merging the PR doesn't necessarily mean this has to be part of any releases if the window between release X.Y and X.Y+1 is used. Feel free to propose the best timing; ideally we'd be more comfortable to have this merged early in the month.
Provided the externalization mechanisms are available between releases, and as we already have stated many-many times, we are happy to work on externalizing the code then.

Also note that due to the involved extra risks, moving the PR's code directly into a separate package (i.e. without merging first) is a scenario we'd really like to avoid as much as possible.

**Comment by unho** [comment]
I am ok with the proposed way forward. Would be good to hear from @phlax.

**Comment by unho** [comment]
Closing this since we forked again.
