### ISSUE TITLE
Put `Review suggestions` action button before others

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4630]
Let's change order of action buttons and put `Review suggestions` before `Needs translation` to encourage going through suggestion backlog.

**Comment by iafan** [comment]
The order of columns in the project browser should also match.

So I suppose what you want in action links is:

1. **Fix critical errors**
1. **Review suggestions**
1. **Continue translation**
1. View all

And the same in the table:

1. Name
1. Progress
1. Total
1. Last updated
1. **Critical**
1. **Suggestions**
1. **Need Translation**
1. Last activity

**Comment by dwaynebailey** [comment]
@iafan Yes, I think it would make sense to change the order of the columns.

I think it's important to understand the why.

We'd like to order things based on priority of action.
1. Fix errors
2. Review suggestions and contributions
3. Continue with new translations

And since we're reading left to right the most important tasks should appear on the top left.

**Comment by iafan** [comment]
I agree with the reasoning.

**Comment by unho** [comment]
> 1. **Fix critical errors**
> 1. **Review suggestions**
> 1. **Continue translation**
> 1. View all

Given the order suggested for the actions shouldn't the table reflect the same order?

1. Name
1. Progress
1. **Critical**
1. **Suggestions**
1. **Need Translation**
1. **Total**
1. **Last updated**
1. Last activity

**Comment by ta2-1** [comment]
@unho I'd prefer to see **Total** in the beginning to see if project is big or not.
We'll be able to move **Last updated** later if we get agreement.

**Comment by dwaynebailey** [comment]
@unho since the three columns are the primary focus of the user because they have the coloured buttons I don't think it matters as much about the other ordering. Though I'm open to look at that, but it seems tangential to the issue being addressed now.

Some points

* I'd prefer minimal churn that focuses on the actual issue we're addressing which is to direct actions. They're already directed by the large colour buttons
* The Totals are subdued but allow the user to see how large a task is. I think we'd still like those first
* Last updated.  I admit I could agree on that moving.  But I still think that is churn that isn't worth as much to reorder.

So lets land with the column ordering we have, since the other changes just don't seem as critical.
