### ISSUE TITLE
Sometimes "Back" button in browser doesn't work

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4793]
- go to browse view page https://mozilla.locamotion.org/projects/ios/
- click on any of `Need works` links to open translate view page
- click on "Back" button in browser

Sometimes it works but sometimes you are redirected on the same translate view page.

**Comment by julen** [comment]
We checked this on our side and it must be a recent regression, as our production server doesn't exhibit this behavior.

Checking the code, something looks quite wrong, as there are more than a consecutive `history.load()` calls being done there (check `setOffset()` for instance), which will append more than a single history entry in the browser, effectively blocking the natural back button behavior.

**Comment by iafan** [comment]
Now that we do have this bug in production, I'd like to raise its priority.

The problem is that when you click on "Needs work", you are being redirected to e.g.
[1] https://translate.evernote.com/ru/web_evernote/translate/#filter=incomplete
which in turns changes the URL to:
[2] https://translate.evernote.com/ru/web_evernote/translate/#filter=incomplete&unit=6174455

Now when you want to go back to URL [1] you are redirected again to URL [2], so you can't go one step back past URL [1].

The solution is likely simple: one has to use `history.replaceState()` instead of `history.pushState()` the first time we load data from the filter that has no unit ID specified.. See https://developer.mozilla.org/en-US/docs/Web/API/History_API for further information.

**Comment by julen** [comment]
Unfortunately though the history API is out of the equation in the current implementation @iafan, since the editor makes use of an ancient jquery-history _"router"_ which only works on top of the `hashchange` event.
