### ISSUE TITLE
Translating last unit says "congratulations" regardless of whether task is actually finished

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4795]
it should only say congrats, if the task is actually completed i would have thought

**Comment by phlax** [comment]
i think this could be resolved by calling get_units with the current query params, on editing the last unit. If there are no more then show the congrats message.

**Comment by unho** [comment]
The issue is not clear, so this is a simple recipe to replicate the issue:

- Open the editor with 3 untranslated units
- Jump to last one
- Translate it
- You get the Congratulations despite not finished translating all 3 units

The expected result is that you only get the Congratulations if you have translated all 3 units.
