### ISSUE TITLE
Reposition Last updated column in stats table

### ISSUE THREAD

**Issue by unho** [translate/pootle#4817]
Some users have reported that now that the **Need Translation** column has been moved to the right, to the left on RTL layouts (see issue https://github.com/translate/pootle/issues/4630), when using small screens (1024px wide) they have to scroll horizontally some times (when some name in first column is long). Perhaps the best way to deal with this is to move the **Last updated** column further right (on LTR) so they can quickly see links to **Need Translation**.

Another possible option is to move the **Total** column further right, instead of **Last updated** column. The upside is that doing this we can align with the order for the action links, where total count is the last one (green lozenge). Note that on https://github.com/translate/pootle/issues/4630 there was some pushback to this proposal.

**Comment by milupo** [comment]
Hi,
I made a screenshot, it is for Upper Sorbian but Pootle interface is in German here. Top right you see a red rectangle - it contains the beginning of the German column caption "Zu übersetzen" (To be translated) of the Need Translation column. This problem does not occur on every Pootle page but here on "devtools/client" it does occur.

![pootle_to_be_translated_column](https://cloud.githubusercontent.com/assets/1248520/16076974/532f6f70-32f6-11e6-8193-280c3445f726.png)

**Comment by ta2-1** [comment]
@unho probably we can make the reposition but we haven't thought about long file names in general.
And the problem will remain for such long filenames.
![image](https://cloud.githubusercontent.com/assets/682845/16078340/16435b92-3307-11e6-96ba-4714a734e8a0.png)
We can try to limit a visible part of filename.

**Comment by phlax** [comment]
can we limit the length of the filenames and append an elipsis where necessary, and then when you hover it could show the full filename

**Comment by unho** [comment]
And display full filename as popup when hovering? Might be an option. Anyway that requires setting a char limit to trim filename, and also it doesn't actually fix the underlying issue which is that some columns are not visible straight away when using small resolutions, something that we will surely hit badly on mobile https://github.com/translate/pootle/issues/4209.

**Comment by phlax** [comment]
more just a tooltip than a popup

**Comment by phlax** [comment]
@unho dont try to plan for mobile in fixing this - a responsive design will handle this totally differently

**Comment by dwaynebailey** [comment]
I suspect with limited horizontal space we'll likely need to do something a bit more innovative.  We could collapse the three columns into one.  And we display the top priority first (Red, Yellow, Blue).

**Comment by milupo** [comment]
The most important column is the Need Translation column. Critical column is pretty useless for translators because strings are checked against English only. Only in very seldom cases it is useful for other languages as well, e.g. if there is a XML-tag error. But most critical errors are placeholder errors (at least for Sorbian languages) which are displayed only because the validator does not know the plural rules. Suggestions column is uninteresting for me - I am interested in translation memory strings in the string view only. Please move the Need Translation column to left (RTL to right).

**Comment by unho** [comment]
@milupo You can mute false positives in critical checks. Since both Sorbian languages are heavily impacted by this I suggest you to take some time and mute the false positives. This is a quick fix for this particular issue, because adjusting the check for Sorbian might take more time.

**Comment by phlax** [comment]
@unho django `truncatechars` will trim and add elipsis

**Comment by milupo** [comment]
@unho I don't use the Critical column. I use the file overview (I don't know the real name of this page) where you can see all errors, also cosmetic ones.

**Comment by unho** [comment]
The proposed quick fix for now is to:

- Move Last Updated column to the right
- Truncate filename column

@dwaynebailey Are you ok with this?

**Comment by dwaynebailey** [comment]
@unho I'm OK with that.

**Comment by iafan** [comment]
Before going with anything else, I'd suggest to limit the `Name` column width to some reasonable percentage value, and provide ellipsis.

For smaller screens, we could provide some other overrides, namely:

1. decrease the width of the progress bar
2. provide alternative smaller captions for `Need Translation`, `Suggestions` and `Critical` columns so that they are appear closer together.
3. Based on the outcome from Items 1 and 2 above, we could even increase the size of the `Name` column.

**Comment by iafan** [comment]
Also: please don't make any quick fixes to the UI without reaching an agreement with _all_ inerested parties.

**Comment by iafan** [comment]
`Last updated` column logically belongs to the source (number of units); moving it closer to the last action will lead to confusion. I believe we can address the issue without shuffling columns at will.

**Comment by iafan** [comment]
@milupo your screenshot suggests you're using larger fonts (either a zoomed in browser view, or system-wide setting). Is that the case?

**Comment by milupo** [comment]
@iafan  Oh, there is a difference, yes, though I allowed sites use their fonts it looks different. Yes, I created a new profile in Firefox and this problem does not occur any more. But, I would prefer, though, to have the Need Translation column more left - it is the most important column for me.

**Comment by iafan** [comment]
@milupo currently our minimal design requirement is 1024px-wide screens with default font size/zoom factor, and the browsing table generally looks good there (unless there are ridiculously long file names as @ta2-1 pointed out in his screenshot). So limiting the width of the first column and using ellipsis needs to be done anyway.

There will never be a canonical column layout that will suit everybody's needs on any randomly small screen resolution. What we can do is to design for the majority, and at least make sure that the UI is rendered in a meaningful way on a minimal size of the screen we support. If we adjust the rendering so that the columns use space more wisely and are visible even on smaller screen sizes (like in your case), the actual ordering of the columns won't matter that much for you, would it?

**Comment by dwaynebailey** [comment]
Could I summarise this as maybe WONTFIX? It seems that our design works in 1024, though it might need some tweaking, especially for smaller sizes.

@iafan hiding those two columns was one of my suggestions with @phlax on smaller screens.  My other ideas where to remove columns that are complete. And maybe to reduce this to one column and only display the next most important action for that row.

@milupo it might help to understand our logic around why we reordered the columns.  In terms of critical things to do 1) You should fix or mute critical errors, 2) You should respond to suggestions, 3) And only then continue translating.  I trust that gives some idea of why we reordered.

**Comment by milupo** [comment]
@dwaynebailey Anyhow I do not understand, why you complicate this problem and want to change things you needn't change. You don't need to change column widths, you don't need collapse or hide collumns. Need Translation column is the most important column and should be in the center of the page and not apart on the right.

How can I mute critical errors? And, I cannot mute crittical errors generally, there could be real critical errors as well. Why isn't it possible to teach the Pootle validator the plural rules? Then a lot fo critical errors would not occur any more.

**Comment by iafan** [comment]
@dwaynebailey I think there are good actionable nuggets in this discussion (like limiting the size of the first column). You can probably open a new case (or set of cases) based on them, for easier tracking.

I'm not very keen of the idea of hiding columns based on the completeness because this will make the table rendered differently based on the context (when one navigates different pages). Hiding some less relevant columns based on browser window size will result in a more predictable behavior. We already do this when we shrink the last action on smaller screens.

**Comment by phlax** [comment]
my 2p 8/

> Need Translation column is the most important column and should be in the center of the page and not apart on the right.

Yep, i agree

>  hiding those two columns was one of my suggestions with @phlax on smaller screens.

i think this is more something we need to think about in terms of creating a responsive design - which if done right (and within some limitations) will work regardless of resolution/screen/font size. I would rather not implement the responsiveness in a piecemeal fashion as it just wont work as expected.

generally also im against hiding information on the basis of screen size

**Comment by dwaynebailey** [comment]
@milupo I was hoping my explanation of what are critical things to action would explain that indeed while translation is the thing you do most, it isn't actually the most critical is there are critical errors or if someone has made a suggestion.  Thus we wanted to make sure that that is what grabs your attention first.  Our general finding has been that translators are no actioning suggestions or addressing critical errors and I hope was to reorder them to make those the first actionable items.

But as @phlax and you point out, certainly in small screen size.  Perhaps its communicating the wrong thing.

To mute an error is quite simple.  Go to the errored unit.  You will see a small symbol to the right of the error.  Click on that and the error will be muted.  When units change the errors will reappear so there really isn't an issue that you will hide errors.  Trust that helps.

**Comment by unho** [comment]
I read the thread twice and I don't see any agreement even in something small. @phlax proposed to truncate the names in the first column and @iafan told to limit its length, and this looks to me like the most agreement-like opinions I read.

Perhaps it is better if you @iafan can come with a clear plan for different window sizes on what to do regarding this.

**Comment by unho** [comment]
I have created PR #4883 with a proposed partial fix.

**Comment by unho** [comment]
Just landed #4883 which partly addresses this. The rest will have to wait until there is a plan on how to address.

**Comment by phlax** [comment]
i think for now this has been addressed
