### ISSUE TITLE
Do not redirect logged in users from login page

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4832]
django expects to be able to send a user from a page which they dont have the required permissions to, to the login page.

atm, if a user is logged in it sends them back to the page they came from, which causes an endless loop.

**Comment by julen** [comment]
A small detail: the permission-related decorators are from django.contrib.auth, however the authentication views are handled by django-allauth.

Django's `user_passes_test()` decorator [redirects users to the login page](https://github.com/django/django/blob/b0acb1e73ef32e368a8a6213e300e66981f976d7/django/contrib/auth/decorators.py#L25). Allauth's sign in view, on the other hand, will automatically [redirect authenticated users back to where they were](https://github.com/pennersr/django-allauth/blob/259b80d47fd8f8e695312848111de30649ddcc36/allauth/account/views.py#L59) (provided the `next` parameter was present).

In Pootle's codebase, the `user_passes_test()` decorator is only used indirectly via `login_required()`, and there's no chance for a redirect loop in this case because only unauthenticated users will be redirected to the sign in page.

Having said that, the loop in #4623 was caused because [the admin view was using `user_passes_test()`](https://github.com/translate/pootle/commit/9f951c3de442401a8db7880164a9b2256a7be20d).

Do you know @phlax if this affects any specific views? If that's the case, Allauth's [`ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS`](https://django-allauth.readthedocs.io/en/latest/configuration.html) can be adjusted; otherwise I'm inclined to close the issue as invalid.

**Comment by phlax** [comment]
hi @julen not any specific views - just more of a fear that this may break 3rd party apps.

As this seems more like an issue in terms of allauth works, closing
