### ISSUE TITLE
Show disabled overlapping data table

### ISSUE THREAD

**Issue by phlax** [translate/pootle#4912]
`Show disabled` overlaps the table on browse pages

see screenshot here
![disabled-overlapping](https://cloud.githubusercontent.com/assets/454682/16900900/87d5a59e-4c2a-11e6-9ecf-5e152391c4b7.png)

**Comment by iafan** [comment]
Since the first `Name` column is usually the widest, I now think it would be better to have this toggle embedded in the column header. This way it will always have room for the link, no overlapping issues, and would work for RTL as well:

![hide_disabled_2](https://cloud.githubusercontent.com/assets/1728158/16902615/6837a04a-4c19-11e6-903e-cffe778f13f7.png)

**Comment by dwaynebailey** [comment]
@iafan would it not work better if the toggle was moved into the navbar?

**Comment by iafan** [comment]
> would it not work better if the toggle was moved into the navbar?

It doesn't quite belong there: all the action links there navigate you to some other page — they are about doing the actual work. This hide/show toggle affects the rendering of the table the same way clicking the table header rows does. Showing the disabled projects, as well as sorting the table, doesn't redirect you anywhere. So keeping this link closer to the table helps set some behavior expectations.
