### ISSUE TITLE
Localizable strings missing for password reset emails

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4933]
Reset password email is partially translated, the other english lines are not in the localization file (even the words like `Hello` or `Thank you for using`...

![Reset Password email](https://dl.dropboxusercontent.com/u/89718989/Screenshot/pootle/bandicam%202016-07-20%2023-47-50-030.jpg)

**I would recommend to check other email templates you added for pootle**... just checked the confirmation pootle email and it is complete, but i do not understand why you add `<br></br>` to break the lines of the text

![Confirmation Pootle email](https://dl.dropboxusercontent.com/u/89718989/Screenshot/pootle/bandicam%202016-07-20%2023-53-47-864.jpg)

**Comment by julen** [comment]
I'm pretty sure the localized strings here are coming from django-allauth, since we don't customize any of the [default password reset emails](https://github.com/pennersr/django-allauth/tree/master/allauth/templates/account/email) and hence the strings over there are not being extracted in Pootle's PO file.

**Comment by unho** [comment]
django-allauth can be translated in https://www.transifex.com/django-allauth/django-allauth/ but as I see Italian is complete. Nevertheless that is master, but translation for the django-allauth version we use does have that string marked as fuzzy https://github.com/pennersr/django-allauth/blob/0.25.2/allauth/locale/it/LC_MESSAGES/django.po#L430-L448 and therefore it is rendered in English in Pootle.

I am not sure if we should override those templates in order to keep the localization within Pootle. I would say it is not necessary. Thoughts?

**Comment by dwaynebailey** [comment]
We have in the past included strings in Pootle for other apps, but I'm almost certain in those cases we included the app in our repo.  We really need to rely on upstream unless there is a simple way to package strings for other apps.  I'm not sure that there is.
