### ISSUE TITLE
Footer sometimes overlaps with statistics table

### ISSUE THREAD

**Issue by unho** [translate/pootle#4943]
In https://mozilla.locamotion.org/projects/firefox/ I always see the footer overlaps the bottom of the statistics table, thus hiding some items:

![overlap](https://cloud.githubusercontent.com/assets/939880/17033010/56d01ed4-4f7c-11e6-9974-ee0d3b9cf0cc.png)

**Comment by iafan** [comment]
As per discussion in the [related PR](https://github.com/translate/pootle/pull/4944), I believe this is a side effect of using non-standard (large) fonts in browser defaults.

I enabled large fonts in Chrome and played around with Pootle a bit. Though I didn't manage to reproduce this exact issue, I'd say in this mode things might look pretty differently 'by design': in this mode the base font size is increased, but all image assets stay the same, so the proportions are damaged, and this affects layout here and there. Compare this to increasing zoom when your page is scaled proportionally, and things generally look good. So if you want to have larger fonts for better readability, I'd suggest you to use zoom in favor of large fonts.

Unfortunately, there's no way to detect larger font size setting using pure CSS, and thus there's no easy way to provide alternative CSS rules if we want to. This requires some JavaScript, e.g.:

```JavaScript
window.getComputedStyle(document.body)["font-size"];
```

which will typically report `13px` for normal font settings, and e.g. `16px` for large fonts (but the value can actually vary).

Given this complication, I'm not sure if we want to support large fonts. It wasn't the goal originally and I'm afraid the target audience with this kind of settings is pretty small. People who use large fonts probably expect minor oddities on random sites.

There's a way to "fix" this by forcing a certain body font size in pixels. This will mean that the browser font setting won't have any effect, and you will see regular (smaller) fonts no matter what. This will, on one hand, ensure the site looks the way we want, but on another, might be a bit worse in terms of accessibility. Not sure if we want to go down that path and lock the font size.

I would also suggest to make sure any issues with layout that we decide to fix are first reproduced on regular font settings, as these are the ones we optimize for, and that the fixes target primarily the default browser settings. Fixes that allow the web site to work better with non-regular font sizes are definitely appreciated, provided they don't degrade experience for the majority of the user base.

Thoughts, everyone?

**Comment by unho** [comment]
Since there are no specific list of steps to reproduce I would say close this issue and the associated PR until I hit this again. If that happens I will try reproducing using default browser settings as suggested, and will reopen the issue in case I manage to reproduce under those conditions.

**Comment by unho** [comment]
I am closing this. Will reopen if I hit this again.
