### ISSUE TITLE
Improve plurals UI

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4976]
Current UI to work with plural forms is very confusing. This is editor area for working with plural forms for Arabic (there are 6 plural forms there).
![image](https://cloud.githubusercontent.com/assets/682845/17171627/392e8bfe-53fa-11e6-9b22-a2c85f47c594.png)

Users should be able to understand that they are editing unit with plural forms and they have to add them. Lets:
- show plural hints explicitly;
- add a separator between plural form editor areas.

**Comment by ta2-1** [comment]
This is how editor looked in 2.5 version.
![image](https://cloud.githubusercontent.com/assets/682845/17171599/1327b8a4-53fa-11e6-964e-744356ac977e.png)

**Comment by dwaynebailey** [comment]
@ta2-1 also there is a visual issue in source, in that its not clear these are 2, or more, plural forms.  Some users have translated both in the target area.

**Comment by ta2-1** [comment]
There is a couple of mockups below that I got from @iafan.
![image](https://cloud.githubusercontent.com/assets/682845/17172052/0f1fad32-53fc-11e6-99ea-97a6777348f1.png)

This will allow us to handle every source plural form separately: report errors, use machine translation, copy sources into targets.
![image](https://cloud.githubusercontent.com/assets/682845/17172133/592b337e-53fc-11e6-8ced-6b50755fa70c.png)

**Comment by dwaynebailey** [comment]
@iafan thanks for the mockups.  Some quick comments:

* The plural forms are likely to have CLDR names namely: zero, one, two, few, many, other.  Not just a numeric value.  In l20n its possible to combine these i.e. it has real numeric instance and CLDR instance e.g. '0', '1', 'many', 'other'
* Source text division:
  * Mockup 1: I worry that any text in or near the source text will get translated, here the 0 and 1
  * Mockup 2: while better of MT and TM (maybe) it's overloading and cluttering the UI.  The line separating them is good. Some ideas: drop 'English' from the second form, put "English - form 1" in the tab, "form 2" in second tab.
* Would be nice if the cluster had the strong border.  And that breaks in target between units was softer.
* My suggestion for a plural form that has no data is that we display a placeholder for that form e.g Plural form 'other', or simply 'other' until the unit has some data.
* I'm curious with an LTR language where you'd propose to put the plural form hints.

**Comment by iafan** [comment]
Thanks for suggestions, Dwayne. These were pretty quick and dirty mockups to ignite discussion.

I share the idea with placeholders — using placeholders + hints should be enough for the input fields and it wouldn't clutter the UI and will be great in terms of LTR/RTL.

This is the third mockup that explores this idea and cleans things up a bit:

![pluralforms3](https://cloud.githubusercontent.com/assets/1728158/17198734/6a5fc85a-542c-11e6-93a0-c8305fa75f6f.png)

The placeholders can be pretty transparent not to create visual noise, but may become more opaque on mouse over.

**Comment by unho** [comment]
I like this much more. Why is "downloaded" highlighted? Will be desirable to highlight placeholders in source strings (%s)? Which is your idea regarding having different TM results for each of the plural forms in this UI?

**Comment by iafan** [comment]
> Why is "downloaded" highlighted?

@unho oh, sorry, please ignore the fact that "downloaded" is highlighted — I just made the screenshot when search function was active in the browser.

> Will be desirable to highlight placeholders in source strings (%s)?

Yes, I'm entertaining the idea of having proper syntax highlighting in both source and target for several years already. But let's put this aside for a moment — this is unrelated to the particular issue. We can discuss highlighting stuff in a separate issue or in Gitter.

> Which is your idea regarding having different TM results for each of the plural forms in this UI?

Apart from making the UI more cluttered, as Dwayne mentioned, I also realized having separate MT / Copy buttons per each form would also require an understanding into which target plural field to paste the result, and this complicates the implementation significantly (because now, when you click on any button, the textarea loses focus). So I decided to put this idea aside as well. In the context of this issue, let's focus on improving the rendering of the source and target plural forms, while keeping the editor behavior the same.

**Comment by iafan** [comment]
@dwaynebailey I forgot to mention that with named plural forms that come from CLDR, the labels can read `Plural form "one"`, `Plural form "many"`, and so on — the updated mockup easily allows for such captions.

Having said that, I must say that I'm a pretty strong opponent of CLDR approach to naming plural forms. The names like "few", "many", "other" provide no real context and are of no help to translator, and "one" is simply misleading and will likely lead to incorrect translations in certain languages. So I personally would avoid showing these whenever possible; this doesn't affect Evernote, however, because our plurals are not PO-based, and we don't use the plural editing UI.

**Comment by dwaynebailey** [comment]
@iafan this looks good.  I agree with you re the confusion of the named plural forms, but its what we have and have to live with.  Its more critical to know that they are that form.

My one concern is that when plurals are entered I assume the name will disappear.  Correct me if I'm wrong.  In which case its unclear which plural form the string represents.

Regardless of that, I think w're good to go on this.

**Comment by iafan** [comment]
@dwaynebailey, yes, for fields with translation the placeholders will disappear, but we can show same text as tooltips on mouseover (I referred to them above as "hints" which might have been confusing).

**Comment by ta2-1** [comment]
![image](https://cloud.githubusercontent.com/assets/682845/18339474/6135572a-75a8-11e6-963f-c4d3ca00a0c6.png)

This is a new version of plural form labels instead of placeholders.

**Comment by ta2-1** [comment]
Fixed in #5202.
