### ISSUE TITLE
Accept/Reject buttons have no valid handlers in SuggestionFeedBackForm 

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#5048]
These are `onclick` listeners for `Reject` button.
![image](https://cloud.githubusercontent.com/assets/682845/17572619/22b9c39c-5f5e-11e6-985f-16e36c680bb3.png)

When you click on Accept/Reject button it is handled as form submit and refreshes a page.

**Comment by ta2-1** [comment]
It was introduced by 66eb7622062e93e355c5a8f3592f8b0192a36182.

**Comment by julen** [comment]
For posterity, it's worth elaborating on the multiple reasons this was happening:

1. React implements a [synthetic event system](https://facebook.github.io/react/docs/events.html) with delegation at the `document` level.
2. Events happening in components (e.g. `click`), need to bubble up to `document` so that React can dispatch the attached handler.
3. Handlers attached via jQuery in the editor are bound to `#editor` since 66eb762.
4. `#editor .js-user-suggestion` has a handler registered for the `click` event.
5. The `SuggestionFeedbackForm` component is rendered **as a children** of `.js-user-suggestion` elements.
6. This means, **any** `click` events performed within the `SuggestionFeedbackForm` component, will bubble up the DOM tree, finding the listener for `#editor .js-user-suggestion` first. Its handler is triggered, `PTL.editor.toggleSuggestion`.
7. The handler always calls `stopPropagation()` on the event object, hence disallowing the event from bubbling up the DOM. The event never reaches any other listeners, including the React event dispatcher.

@ta2-1's solution has been to stop event's propagation only when we know for sure the code doesn't need any interaction from the `SuggestionFeedbackForm` component (because e.g. it's not rendered).

**Comment by phlax** [comment]
thanks for the explanation @julen
