### ISSUE TITLE
Not Found error coming up un-necessarily

### ISSUE THREAD

**Issue by leonardcj** [translate/pootle#5134]
Using DHIS2 pootle instance Pootle 2.8.0b3 is powered by Translate Toolkit 2.0.0b3.  going from template to lang-en

https://translate.dhis2.org/en/

I have repeated occurrences of entering a string (copied/pasted from msgid) and clicking Submit, only to get a "Not Found" message and a greyed out Submit button.

If I move a string up or down and retry, it works out ok. But this is happening a lot and it is not correct behavior (IMHO).

**Comment by julen** [comment]
Hi @leonardcj, I have the feeling this is amaGama trying to load a URL like `.../api/v1/en/en/...` which returns 404. Could you please confirm?

In such cases no error should be displayed since #4771 was fixed, so I wonder whether the server is using the latest code. @translate/house might be able to shed more light on the amaGama side.

**Comment by phlax** [comment]
i think this bug is now fixed in current master and latest rc releases.

@leonardcj please ping or reopen if its still an issue
