### ISSUE TITLE
Severe performance degradation of sync_stores

### ISSUE THREAD

**Issue by iafan** [translate/pootle#5178]
Earlier today we updated production translation server (merged 'Raw font' PR branch with master and switched to master). So this release includes recent changes related to optimizations. Immediately after that our sync cycle time increased from typical 18-20 minutes to 1.5 hours. I had to write a tool to analyze and compare our logs from past sync cycles and extract timing information. Here's the output:

![screenclip](https://cloud.githubusercontent.com/assets/1728158/18117500/035f5506-6f04-11e6-98db-5303e76872f7.png)

Some comments on the screenshot. It compares our main steps of sync cycle between four logs (vertical columns). The first log is from a morning run, some time before the release. The second one is soon after the release, and the last two are most recent ones. As one might see, the `pull-ts` step is the culprit. It went from mere 3 minutes up to more than an hour. During this step all we do is run `manage.py sync_stores --skip-missing --project=<project_id>` and wait for it to finish.

**Comment by julen** [comment]
I can see the degradation is caused by unnecessary disk IO. Optimizations are definitely not kicking in.

Comparing the relevant [code in master](https://github.com/translate/pootle/blob/b1ccad76424c0f9e12646b40f4f632e23ecbd219/pootle/apps/pootle_store/syncer.py#L256-L259):
```python
    if only_newer and not self.update_newer(last_revision):

...

    def update_newer(self, last_revision):
        return (
            not self.store.file.exists()
            or (last_revision >= self.store.last_sync_revision)
```

With [what we had in the previous release](https://github.com/translate/pootle/blob/evernote-release-2016-08-15/pootle/apps/pootle_store/models.py#L1855-L1856):
```python
        if (only_newer and self.file.exists() and
            self.last_sync_revision >= last_revision):
```

Shows that the logic has been altered in a bad way.

**Comment by phlax** [comment]
@julen i can fix if you want
