### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'args' in social authentication

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#5242]
Ok after asking for help to allauth github about my custom oauth provider, they said me that problem was related to pootle. This is the comment: https://github.com/pennersr/django-allauth/issues/1478#issuecomment-246207030 and scrolling up you will find the python code used for my custom provider... i don't know what else to do... thank you in advance

**Comment by dwaynebailey** [comment]
Actually the problem really isn't related to Pootle.  Pootle receives and authentication failure and tries to report it but the variable `exception` is `None`.  I'd put some `print` statements there so that you can quickly see what those variables contain.  Since its the auth provider you've created I wouldn't be surprised if its failing and then failing to report that failure properly.  Pootle is just at the end of that failure path.

**Comment by phlax** [comment]
adding the traceback here so we can help diagnose the issue

```
...
   File "/home/desktop/Pubblici/Envs/pootle/lib/python2.7/site-packages/pootle/apps/accounts/social_adapter.py", line 77, in authentication_error
     log_exception(request, exception, tb)
   File "/home/desktop/Pubblici/Envs/pootle/lib/python2.7/site-packages/pootle/middleware/errorpages.py", line 49, in log_exception
     msg_args = (unicode(exception.args[0]), tb,
 AttributeError: 'NoneType' object has no attribute 'args'
```

**Comment by JohnnyKing94** [comment]
I just fixed with this editing: https://github.com/pennersr/django-allauth/issues/1478#issuecomment-246423503

Cheers :smile:
