### ISSUE TITLE
execfile is not defined

### ISSUE THREAD

**Issue by Nuruddinjr** [translate/pootle#5984]
Python 3.5.2 , Pootle 2.7.6 runs the following issue
![image](https://cloud.githubusercontent.com/assets/9083431/23042174/42233f80-f45d-11e6-9450-8563ef4347a0.png)

**Comment by dwaynebailey** [comment]
@Nuruddinjr Pootle doesn't support Python 3 at this time.

Feel free to help port it to Python 3 we'd welcome any PRs.  If the docs don't make the Python 2.7 requirement clear please we'd welcome any PRs.

Most helpful Python 3 fixes at this time would be those that work in Python 2.7 and Python 3.  And we usually make sure to keep them fixed with a pylint error check.
