### ISSUE TITLE
Is there a related string?

### ISSUE THREAD

**Issue by milupo** [translate/pootle#6084]
Hi,

the next issue from me: :-)

in Fx 54 the following two strings exist:

**aboutSupport.sandboxSyscallIndex** _"#"_ and
**aboutSupport.sandboxSyscallAge** _"Seconds Ago"_

Are both strings related and will they form a string like "**# [number of seconds] Seconds Ago"**? It is important to know because Sorbian languages use a preposition (před, pśed) instead of a postposition. Besides the plural rules should be usable then.

**Comment by unho** [comment]
Hi @milupo 
We try to manage requests like adding new projects, or general questions about Mozilla projects, through the tech-team@translate.org.za alias. You can send an email directly or use the contact form in https://mozilla.locamotion.org/.

That ensures that your request is visible not only to Pootle admins but also to Mozilla staff. It will also allow faster responses, since multiple people receive messages sent to that address.

I am forwarding your request now and closing this issue. You should receive a proper response shortly.

Thanks

**Comment by milupo** [comment]
> Leandro Regueiro <notifications@github.com> hat am 15. März 2017 um 09:30 geschrieben:

> We try to manage requests like adding new projects, or general questions about Mozilla projects, through the tech-team@translate.org.za alias. You can send an email directly or use the contact form in https://mozilla.locamotion.org/.
> 
> That ensures that your request is visible not only to Pootle admins but also to Mozilla staff. It will also allow faster responses, since multiple people receive messages sent to that address.
> 
> I am forwarding your request now and closing this issue. You should receive a proper response shortly.

Hi Leandro,

thank you for your reply, your information and the forwarding. Francesco sent me an email that the strings are unrelated.

Regards,

Michael
