### ISSUE TITLE
xliff: support state attributes for target nodes

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#617]
*Originally posted by André Schnabel:*

it would be a grweat enhancement for translation workflow,if pootle was able to support xliff's state attribute for a translation unit's target.

support should include:
- ability to set a state manually (at least translated, needs-review-l10n, signed-off, final)
- abiltity to set / detect automatic states (new,  needs-l10n)
- build statistics on this states
- include these states "to tranlate" and "to review" filters

the non-plus-ultra was to support even state-qualifier attributes

**Comment by dwaynebailey** [comment]
Our model going forward is to have Pootle itself manage a set of states that make the most sense for general translation.  These should then map back to the states present in a format.  So rather than polluting Pootle with XLIFF states we'll rather have Pootle export correct states to XLIFF and allow Pootle to understand on its own terms states that might come from XLIFF.
