### ISSUE TITLE
Fix display localized language names in dropdown

### ISSUE THREAD

**Issue by unho** [translate/pootle#6218]
Noticed as part of https://github.com/translate/pootle/pull/6217 testing that it wasn't working.

**Comment by dwaynebailey** [comment]
Do you have the package installed for localised names?

**Comment by phlax** [comment]
that might be the issue - but then doesnt that suggest a missing dep ?

**Comment by dwaynebailey** [comment]
@phlax yip could be, though IIRC its best provided by a Debian package, so not sure its available via pypi.

**Comment by phlax** [comment]
maybe we should a check/warning ?

**Comment by dwaynebailey** [comment]
@phlax makes sense to do it as a check.

For the record from TTK README:

>Functions in the lang.data module can supply functions to translate language
names using the iso-codes package. It can even translate names in the format
``Language (Country)``
such as
``English (South Africa)``
This is used by Pootle and Virtaal. If the package is not installed, the
language names will simply appear in English. It is therefore recommended you
install the iso-codes package for your distribution, but it is optional.
Alternatively, it is also available from http://packages.debian.org/unstable/source/iso-codes

**Comment by phlax** [comment]
seems like the problem (or at least one) here relates to the way pythons gettext finds the iso-code translation files

because they can live anywhere, pythons gettext uses the convention of `sys.prefix + "share/locale"`, which ordinarily would resolve to `/usr/share/locale`

in a virtualenv `sys.prefix` can be mangled, and it therefore cant find the translation files
