### ISSUE TITLE
Use common country name instead of official

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#6532]
From the channel when discussing localisation of Chinese (Taiwan) with @zerng07 

>@dwaynebailey Great! I found the new string comes from "the name for TWN, official_name for TWN" instead of the old "common_name for TWN" in iso_3166.
However, it is better to use "common_name for TWN" actually. (Widely used and accepted in Taiwan)

**Comment by zerng07** [comment]
This is the language list in Pootle 2.5, which uses Chinese (Taiwan) for my language, zh_TW. The translation of Chinese (Taiwan) is "漢語 (臺灣)". The other Chinese locales are Chinese (China) and Chinese (Hong Kong) which correspond to "漢語 (中國)" and "漢語 (香港)".
![pootle 2 5](https://user-images.githubusercontent.com/1706450/27516865-78ba07d4-59f4-11e7-8389-28d7acb34426.png)

And this one is the language list in Pootle 2.8, which uses Chinese (Taiwan, Province of China) for my language, zh_TW. The translation now is "中文 (中華民國)". The other Chinese locales are Chinese (China) and Chinese (Hong Kong) which correspond to "中文 (中國)" and "中文 (香港)".
![pootle 2 8](https://user-images.githubusercontent.com/1706450/27516866-7f882f5a-59f4-11e7-8dbb-a89439a2d49c.png)

It is more widely used and accepted with the common name for people in Taiwan, so please use the common name for TWN instead of the official_name for TWN. Thanks!
