### ISSUE TITLE
Deprecate update/sync stores

### ISSUE THREAD

**Issue by phlax** [translate/pootle#6690]
Wondering what is best with these commands.

on the one hand they are quite useful for grouping common operations

on the other, it would be better for users to learn the more powerful fs api, and grouping can be done in other ways

**Comment by dwaynebailey** [comment]
My thoughts @phlax are these:

1. We certainly need to keep them around to allow transition, even just so that scripts work and results are mostly as expected.
2. I do find myself doing, fetch, resolve, sync, so yes a grouping command like update_stores would simplify things.
3. One option would be update_stores does fs-win, and sync_stores does ptl-wins, with needed add's and rm's thrown in.  But while that achieves the nice grouping it overloads what people think.
4. If we want to group maybe `pootle fs update` and `pootle fs download` (sync's taken) could be the cluster equivalents?
