### ISSUE TITLE
Check list not working as it should be

### ISSUE THREAD

**Issue by OfficalAhmad** [translate/pootle#6810]
So I am translating on Pootle for OpenOffice (an Open Source project managed by the ASF). I have noticed a potential error with the check list feature of Pootle, as when i am translating a string, usually if i put a full stop (.) at the end of a sentence, and there is no full stop at all in the English version, the check list featur would fail, indicating to an 'ending punctuation'. I tried, instead of a full stop, numbers, and i put the numbers in a string, where the original string contains no numbers whatsoever, and i expected to get a failing check list due to numbers being in there. However i did not get that. 

OpenOffice deploy a different version of Pootle, however, which is version 2.5.1.3, and i am aware that the latest version of Pootle is 2.8.2. Can anyone confirm whether this issue exist on the latest version of Pootle?

**Comment by comradekingu** [comment]
The ending punctuation check is working as it should. It is there to make you add or remove the dot, so that it corresponds to the source string.

Numbers can be written in full or not, seems just doing a basic check there would be counterproductive.

LibreOffice (the updated GPL fork of OpenOffice), uses a recent version of Pootle https://translations.documentfoundation.org

I would advice you to put your energy into that.
